### PR TITLE
Fix deprecation warnings due to not using collections.abc

### PR DESCRIPTION
**Pull request by Strilanc**
This were suddenly very visible, due to the --actually-quiet argument on the pytest checks.

### CODE REVIEW

**Comment by cduck** [comment]
```
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/google/protobuf/descriptor.py:47: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from google.protobuf.pyext import _message
/home/travis/build/quantumlib/Cirq/cirq/ops/op_tree.py:111: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(root, collections.Iterable):
/home/travis/build/quantumlib/Cirq/dev_tools/shell_tools.py:72: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  async def _async_forward(async_chunks: collections.AsyncIterable,
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/jsonschema/compat.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping, Sequence  # noqa
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/jsonschema/compat.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping, Sequence  # noqa
```

**Comment by Strilanc** [comment]
I can't do much about the dependencies, but I cleaned up the remaining ones within cirq.

**Comment by cduck** [comment]
Still missed one:
```
/home/travis/build/quantumlib/Cirq/cirq/ops/qubit_order.py:127: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(val, collections.Iterable):
```

Are there newer version of protobuf and jsonschema that we can pin?

**Comment by Strilanc** [comment]
Oh it's only warning on the first use; there was actually a ton more.

**Comment by Strilanc** [comment]
I don't want to change the protobuf version without checking with Mike first.

**Comment by cduck** [comment]
Changing package versions doesn't need to be in this PR.  Open an issue.

**Comment by Strilanc** [comment]
https://github.com/quantumlib/Cirq/issues/1831

**Comment by cduck** [comment]
Also tenserflow_core on Windows.

**Pull request merged**
