### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by tonybruguier**
Related to issue #3716

### CODE REVIEW

**Review by viathor — APPROVED** [review]

**Comment by vtomole** [comment]
How do these keep keep through the CI?

**Comment by balopat** [comment]
> How do these keep getting through the CI?

It's a mystery for now!

**Comment by viathor** [comment]
A guess: perhaps pylint doesn't recognize all syntax involving types and to avoid producing incorrect warnings it just lets us import anything we want from `typing`.

**Comment by tonybruguier** [comment]
The pylint on my machine did find the issues from this PR. I'm not sure why it hasn't been done e by the pylint in GitHub.

**Comment by balopat** [comment]
cc #3716 
cc #1986 maybe is back to haunt us?

**Pull request merged**
