### PR TITLE
In unitary_eig, check preconditions before performing computing eigenvalues

### PR DESCRIPTION
**Pull request by kevinsung**
They are _pre_-conditions after all.

Also defines `cirq.is_normal`.

### CODE REVIEW

**Comment by kevinsung** [comment]
The diagonal check is not cheaper because it requires first computing the factorization, which is much more expensive than checking whether the matrix is normal. The purpose of performing the check should be to prevent the expensive computation from happening in the event of a failed check.

**Comment by viathor** [comment]
I disagree. You're only taking into account the cost when the matrix fails to be normal. In this case before the PR we indeed pay the full cost of the Schur decomposition which is greater than the cost of commutativity check. However, the commutativity check costs more when the matrix is in fact normal. Consequently, as long as we think that non-normal inputs are *rare* this PR increases the overall cost.

(That said, I don't think the increase is going to be a problem in practice.)

**Comment by kevinsung** [comment]
Ah, I see what you're saying. I still prefer the semantics of the change that I made (and again, users can always disable the check).

**Comment by viathor** [comment]
Yes, I agree with your PR: it is weird that `check_precondition` checks a post-condition. I don't think we were discussing a significant cost and in any case it can be disabled, so LGTM.

**Pull request merged**
