### PR TITLE
Fix serialization breakage due to sympy.Rational now being a numbers.Number

### PR DESCRIPTION
**Pull request by Strilanc**
- Reorder the sympy checks to come before generic number checks
- Rename json.py to json_serialization.py to avoid collisions with the built-in json library
- Detect integral values when deserializing symbolic protos, so that x - y does not become x - 1.0*y.
- Pin to 1.4 until https://github.com/sympy/sympy/issues/18056 is fixed

Fixes https://github.com/quantumlib/Cirq/issues/2650
Fixes https://github.com/quantumlib/Cirq/issues/2646

### CODE REVIEW

**Comment by KevinVillela** [comment]
Yayyyy thanks!

**Comment by Strilanc** [comment]
> I imagine sympy changed something so isinstance(obj, numbers.Integral) now returns True for sympy.Integer?

Yeah something like that.

**Comment by Strilanc** [comment]
The OSX build is failing for some unknown reason

image

I have disabled it in this PR and will open an issue to re-enable it.

**Comment by Strilanc** [comment]
You are killing me here, cirqbot.

**Comment by Strilanc** [comment]
Urgh, just found https://github.com/sympy/sympy/issues/18056 which puts a big blocker on using the new version of sympy. I am going to pin to the old one.

**Pull request merged**
