### PR TITLE
Add missing quote in circuits.ipynb

### PR DESCRIPTION
**Pull request by LaurentAjdnik**
Adds a missing quote in the Circuits notebook that causes incorrect display of the doc:

TempCirqOperations

### CODE REVIEW

**Review by vtomole — APPROVED** [review]
LGTM. Thanks!

**Comment by LaurentAjdnik** [comment]
@googlebot I signed it!

**Review by vtomole — CHANGES_REQUESTED** [review]
Actually, one small thing: Could we change `Operations` to `Operation`s because `cirq.Operation` exists, but not `cirq.Operations`.

**Comment by LaurentAjdnik** [comment]
> Actually, one small thing: Could we change `Operations` to `Operation`s because `cirq.Operation` exists, but not `cirq.Operations`.

I sure can. But `Operations` already appears as such eight times. Just like `Moments` is used twice instead of `Moment`s.

Should I change them all? I agree this would be more logical.

**Comment by vtomole** [comment]
Oh i see. That's fine then. Let's leave it as-is because I bet the conventions that exist at the moment are not restricted to this file.

**Review by vtomole — APPROVED** [review]

**Pull request merged**
