### PR TITLE
Use sorted instead of set for random.sample

### PR DESCRIPTION
**Pull request by dabacon**
Sampling on a set is being deprecated (https://docs.python.org/3/library/random.html), this removes warnings and uses a deterministic ordering from sorted.

### CODE REVIEW

**Review by MichaelBroughton — APPROVED** [review]
Why sort and not just convert to unordered list ?

**Comment by dabacon** [comment]
> Why sort and not just convert to unordered list ?

To get a deterministic ordering, which is what is suggested in the python docs for this case.

**Comment by MichaelBroughton** [comment]
Did this merge bleed over somehow ?

**Comment by dabacon** [comment]
> Did this merge bleed over somehow ?

The black trailing comma cl made it grow exponentially.

**Pull request merged**
