### PR TITLE
Change qubit str representation

### PR DESCRIPTION
**Pull request by dstrain115**
- Changes grid qubit string representation from (x, y) to q(x, y)
 and line qubit from 1 to q1.
 - This will make the string representation more distinctive.
 - Added _circuit_diagram_info_ for Qid objects to make circuit diagrams
customizable for qubits.  This allows us to keep circuit diagrams
largely unchanged.
 - Other components such as pauli strings, that rely on qubit str
   representation for formatting are changed.

 This is a BREAKING CHANGE for anyone relying on string representation
 of qubits.  This also changes default measurement keys and the '.measurements()'
functionality of results, since these use the string representation of qubits.

Fixes: #2405

### CODE REVIEW

**Review by maffoo — COMMENTED** [review]
With the [`q` function](https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/ops/qid_util.py#L22), line qubits would look like `q(0), q(1)` instead of `q0, q1`. Do we want to use the parenthesized form instead?

One place we should think carefully about is that qubit string representations get included in measurement keys by default if no key is specified. I think this should be ok, but there may be some places where we assume the form of these measurement keys.

**Comment by dstrain115** [comment]
Ok, I have cleared out all the test failures, and this is now ready for review.

**Review by maffoo — APPROVED** [review]
This looks good to me, just a few minor comments and one question about whether we want to revert to the `(x, y)` form for grid device diagrams (as we use in circuit diagrams). Also, I think it'd be good to have some other folks look at this before we do it, since the measurement key changes in particular may pose compatibility concerns for results that were saved with the old format. @zchen088, would this be an issue for datasets we've saved internally?

**Comment by dstrain115** [comment]
@maffoo This change was announced at cirq-cync, but I am open to other modes of communication, especially internally.

**Comment by dstrain115** [comment]
I will be submitting this change soon, so chime in if you have any requested changes.

**Pull request merged**
