### PR TITLE
Delay import of scipy stats and optimize

### PR DESCRIPTION
**Pull request by dabacon**
This speeds up top level import.

Note that we had previously done this for another use of scipy.stats, but this one got added.  Also doing it for scipy.optimize.  Both of these can slow down the resulting experiments, probably a case for moving experiments out of cirq-core?

### CODE REVIEW

**Comment by dabacon** [comment]
```
python -c 'import time; time.sleep(1); t1 = time.monotonic(); import cirq; t2 = time.monotonic(); print(t2-t1)'
```
Before the PR gives 1.7412576620699838 and after gives 1.355757946963422

**Comment by dabacon** [comment]
Current slowness besides these scipy modules are
sympy: 0.386s
numpy: 0.169s
pands: 0.204s
matplotlib.pyplot 0.334s
networkx: 0.079s

**Comment by MichaelBroughton** [comment]
This looks good. Did you have the time to checkout something like this: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/lazy_loader.py#L23

Which would give us the added bonus of being able to start rounding up all the random imports we have littered everywhere to avoid circular imports (putting them back at the top with this) ?

**Comment by dabacon** [comment]
> rounding

Untested TensorFlow code!  My eyes they burn! The googles they do nothing!   Do you see the benefit of the TensorFlow class?  I guess if you use the class in a lot of places?

**Comment by MichaelBroughton** [comment]
> Do you see the benefit of the TensorFlow class?

Well you don't have to worry about where in the module you'd need to put your imports if you used this class. The actual load would take place when the call is made. So in this case of scipy instead of having to put multiple imports in weid places just do at the top:

```python3
# can do circular imports at the top with this too.
scipy_linalg = LazyLoader("scipy.whatever", globals())

def my_function(...):
   stuff.

def my_scipy_function(...):
  return scipy_linalg.whatever # this triggers actual import.
```

**Comment by dabacon** [comment]
Created #4648 to consider adding LazyLoader.

**Review by MichaelBroughton — APPROVED** [review]
LGTM, we should probably hold off on more like this for now until a decision is made on the LazyLoader approach (otherwise we might just be making more work for ourselves here).

**Pull request merged**
