### PR TITLE
Add a process fidelity utility function

### PR DESCRIPTION
**Pull request by tonybruguier-google**
This is for issue #2763

### CODE REVIEW

**Comment by mpharrigan** [comment]
What are U and V? time-evolution operators that are nearly unitary? I skimmed the linked preprint and I don't think this is exactly what we'd want as the main `process_fidelity` function. It should be defined on two CPTP maps aka quantum channels aka something that turns one density matrix into another. 

The function from qiskit is probably a good starting point: https://qiskit.org/documentation/stubs/qiskit.quantum_info.process_fidelity.html#qiskit.quantum_info.process_fidelity. Of course, this would require introducing a superoperator representation for processes. The different representations are described here, for example https://arxiv.org/abs/1111.6950

**Comment by viathor** [comment]
I agree with @mpharrigan. Any utility for process fidelity needs to be explicit about what representation of a CPTP map it accepts. Also, a few [common maps](https://github.com/quantumlib/Cirq/blob/master/cirq/ops/common_channels.py) are already implemented in cirq. We should use one representation consistently throughout the library and if you find that the present representation is insufficient we should generalize it appropriately rather than adding another.

**Comment by tonybruguier** [comment]
Hello,

Sorry for the delay. I have now a new user name and it took me a while to understand the paper you gave me (sorry and thank you for the help). I would suggest closing this PR and moving the review to:
https://github.com/quantumlib/Cirq/pull/3226

**Comment by balopat** [comment]
> I would suggest closing this PR and moving the review to:
> #3226

Sounds good - closing this one.

**Pull request closed without merging**
