### PR TITLE
Added Quantum Walks Tutorial

### PR DESCRIPTION
**Pull request by Lucaman99**
New PR

### CODE REVIEW

**Comment by Lucaman99** [comment]
@vtomole Ok, this seems to be working

**Comment by Lucaman99** [comment]
Finally 😂

**Comment by Lucaman99** [comment]
@vtomole Fixed it

**Comment by Lucaman99** [comment]
@vtomole Should this be good for merge?

**Comment by vtomole** [comment]
@Lucaman99 Did you run this through a grammar checker? I just noticed a typo in the comment i pasted. You say `# Defines the total number of steps our walked will take` but it should be `walk`.

**Comment by Lucaman99** [comment]
Yeah I passed it through a grammar checker, must have missed it, I'll fix it

**Comment by Lucaman99** [comment]
@vtomole Ok, done

**Comment by vtomole** [comment]
@Lucaman99 Thanks for you patience.

**Comment by Lucaman99** [comment]
@vtomole Of course, thanks for all your help!

**Pull request merged**
