### PR TITLE
Small housekeeping in check/pytest

### PR DESCRIPTION
**Pull request by pavoljuhas**
- Clean up special-casing for Python 3.6 as we require Python 3.7.

- Simplify handling of the parallel job count `-n COUNT` option in check/pytest.
  Obey the `-n0` option on the command line in addition to `-n 0` to
  request non-parallel testing.

### CODE REVIEW

**Comment by pavoljuhas** [comment]
@vtomole - can you PTAL?

**Review by vtomole — DISMISSED** [review]
LGTM

**Review by vtomole — COMMENTED** [review]
How do i call this correctly?

```python

(cirq_venv) vtomole@vtomole:~/Cirq$ ./check/pytest -n0
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n0 -n=auto
  inifile: /home/vtomole/Cirq/pyproject.toml
  rootdir: /home/vtomole/Cirq
```

**Comment by pavoljuhas** [comment]
> (cirq_venv) vtomole@vtomole:~/Cirq$ ./check/pytest -n0
> ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
> pytest: error: unrecognized arguments: -n0 -n=auto

The `-n N, --numprocesses=N` option comes from the pytest-xdist plugin.

Please try again after `pip install -r dev_tools/requirements/deps/pytest.txt`

**Review by vtomole — APPROVED** [review]
Works :+1:

**Pull request merged**
