### PR TITLE
Move flynt from `format-incremental` to `lint`

### PR DESCRIPTION
**Pull request by vtomole**
- Renames `pylint` and `pylint-changed-files` scripts to `lint` and `lint-changed-files` respectively.
Fixes: https://github.com/quantumlib/Cirq/issues/3901

### CODE REVIEW

**Comment by balopat** [comment]
This is a bit simpler - format-incremental is already incremental: https://github.com/quantumlib/Cirq/pull/3905

**Comment by balopat** [comment]
@vtomole flynt is better in the format-incremental because it can benefit from the `--apply` flag.

**Comment by balopat** [comment]
Sorry @vtomole I didn't see your PRs when I pushed my solution, but in the end I prefer that approach because it's simpler in my opinion. It also handles the `--apply` and `--dry-run` behaviors.

**Comment by vtomole** [comment]
@balopat 👍

**Pull request closed without merging**
