### PR TITLE
Refactor private static methods to module functions.

### PR DESCRIPTION
**Pull request by thanacles**
Refactor private static methods to module functions. 
Related to #3324.

### CODE REVIEW

**Comment by thanacles** [comment]
This change looks pretty scary but the vast majority of it is just tabbing.  Moving the function out of the class means that we can remove one tab from all of the function lines.

**Comment by thanacles** [comment]
It looks like I don't have permission to attach this to an issue.  This PR is related to https://github.com/quantumlib/Cirq/issues/3324

**Comment by daxfohl** [comment]
This probably needs confirmation from the core maintainers regarding how aggressive they want to be here. Any deprecation eventually affects users and even "private" methods are sometimes widely used, It may be worth bringing up in cirq sync if you can attend, unless one of the maintainers wants to jump in here.

**Comment by thanacles** [comment]
OK, I'll bring it up in next cirq sync.

**Comment by thanacles** [comment]
@balopat @daxfohl From the discussion.  This change would be the first step toward fixing this issue would.  Namely this performs the refactor on private functions.

**Review by balopat — APPROVED** [review]
LGTM

**Comment by maffoo** [comment]
There are a few cases here where "private" static methods are used by other modules, so they're not really private to the module. In some places this PR modifies the other modules to import those private static methods directly, but this conflicts with the style guide recommendation to import modules rather than importing names from modules. IMO it's cleaner in some of these cases to leave these functions as static methods on a class and use them that way, though we could also change some of the imports to be module imports (sadly, some have awkward names like `cirq.circuits.circuit` since `circuit` is a very common variable name). Anyway, I'll refrain from bikeshedding further and defer to what other folks want to do.

**Comment by thanacles** [comment]
I feel like usage of private methods outside of its module is a pretty categorical anti-pattern.  I'll take a pass through the code to see if there is a way to stop this from happening.

**Comment by thanacles** [comment]
@maffoo I updated the imports to only import modules.

@balopat This PR is ready to be merged.

BTW, can someone give me a link to the styleguide?

**Pull request merged**
