### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by MarinaM79**

### CODE REVIEW

**Comment by dstrain115** [comment]
Before merging this, I think this project needs to iron out what the best practices for security updates and reporting should be.  Do you have any links to what prompted this update?

**Comment by pavoljuhas** [comment]
The file might have been generated per https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by NoureldinYosri** [comment]
@MarinaM79 could you elaporate on why we need this?

it looks like the file in the PR is a template

**Comment by pavoljuhas** [comment]
cirq-csynque - we need to determine if this is necessary for cirq.

**Pull request closed without merging**
