### PR TITLE
Skip "magic trailing comma" when formatting with black

### PR DESCRIPTION
**Pull request by maffoo**
The "magic trailing comma" is a comma at the end of bracketed list that forces black to format the list entries on separate lines, even if they would fit on one line. For example, if you write:
```python
foo(a, b,)
```
black will see that trailing comma and format this as:
```python
foo(
    a,
    b,
)
```
But with the `skip-magic-trailing-comma` setting enabled this will format on a single line instead
```python
foo(a, b)
```
IME the trailing commas are almost always unintentional, e.g. left over from other refactos, and result in wasted vertical space. I suggest we enable this flag.

### CODE REVIEW

**Comment by maffoo** [comment]
For an example of how this changes the formatting, see https://github.com/quantumlib/Cirq/pull/5171.

**Comment by maffoo** [comment]
Curious if other @quantumlib/cirq-maintainers have opinions here. @MichaelBroughton is skeptical, based on his comments on #5171.

**Comment by dabacon** [comment]
Amazing to see how many places people put trailing commas when they aren't really a good idea (other PR).

My main objection to this is that making black more and more configured means that I have to constantly switch between different black configs across different repos.  Typically I use virtual envs so this isn't a problem, but my IDE has a global black (reasons *sigh*) for running on save.  

One question: if you turn the trailing commas back on does black add them back in?  i.e. could we just do a cleanup of this and try to start enforcing better standards?

**Comment by maffoo** [comment]
> if you turn the trailing commas back on does black add them back in? i.e. could we just do a cleanup of this and try to start enforcing better standards?

If you format with `skip-magic-trailing-comma = true`, then turn the option off again the formatting will not change, so yes, one can turn on the option locally and reformat and the format check will still pass in CI. `black` never _inserts_ a magic trailing comma on it's own (that's why they're magic), but it _does_ insert trailing commas in expressions that are too long to fit in a single line (long lists, tuples, arg lists, etc), and this is where hysteresis can enter in to the formatting:

- black reformats a long line and adds a trailing comma.
- subsequent refactor shortens the code so the expression _would_ fit on a line.
- `s-m-t-c=true` would reformat this to a single line again, while the default `s-m-t-c=false` will consider the comma originally added by black as "magic" and leave the multi-line expression.

**Comment by maffoo** [comment]
> but my IDE has a global black (reasons sigh) for running on save.

As noted above, you could set `skip-magic-trailing-comma = true` globally, and black with either configuration will accept it (of course there could be other differences in black configuration that will not work globally like this, such as line length or string normalization).

**Comment by maffoo** [comment]
Ping @MichaelBroughton; thoughts on this?

**Review by MichaelBroughton — APPROVED** [review]

**Comment by dabacon** [comment]
Are we going to do a global format or just fix these as we go around, just got hit by this :)

**Comment by maffoo** [comment]
I would vote for global format. Since we have `.git-blame-ignore-revs` this doesn't affect blame too much. I did `cirq-google` in https://github.com/quantumlib/Cirq/pull/5171.

**Pull request merged**
