### PR TITLE
Rm build_rtd_docs CI job and its dependencies

### LINKED ISSUE #6416: Remove build_doc CI job and dependencies
**Description of the issue**
Sphinx version update caused a [CI error](https://github.com/quantumlib/Cirq/actions/runs/7452039565/job/20274451752?pr=6399#step:5:15) with the `build_docs.sh` job. This job is no longer used since we instead use the quantumai website. Remove this job and it's dependencies (i.e Sphinx) 

**Cirq version**
1.4.0.dev20231221183905

### PR DESCRIPTION
**Pull request by senecameeks**
Fixes #6416

### CODE REVIEW

**Review by pavoljuhas — CHANGES_REQUESTED** [review]
Looks good, but there are few more leftovers - 
```
$ git grep -n -i "readthedocs.{0,30}cirq|rtd" | grep -v -i image/png
.dockerignore:24:rtd_docs/generated
.gitignore:25:rtd_docs/generated
.readthedocs.yml:7:      - requirements: rtd_docs/requirements.txt
.readthedocs.yml:9:  configuration: rtd_docs/conf.py
README.rst:19:.. image:: https://readthedocs.org/projects/cirq/badge/?version=latest
README.rst:20:  :target: https://readthedocs.org/projects/cirq/versions/
dev_tools/incremental_coverage.py:24:    r'^rtd_docs/.+',  # Environment-heavy code.
```

We should remove the `.readthedocs.yml` configuration file as there is nothing to build at RTD now. :-)

**Comment by pavoljuhas** [comment]
The hanging `Build docs` CI job may need to be somehow deactivated in our GitHub page.

@dstrain115 , @95-martin-orion - can you PTAL?


image

**Comment by senecameeks** [comment]
Re: @pavoljuhas comment-- someone _should_ be able to disable the workflow by navigating to the `Actions` tab on github and [disabling the workflow](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow). I don't think I have sufficient permissions to do it myself since I'm not seeing an option to do it. 

@dstrain115 , @95-martin-orion can either of you disable the deprecated `Build Docs` CI job on the GUI?

**Review by pavoljuhas — APPROVED** [review]
LGTM, Thank you!

**Pull request merged**
