### PR TITLE
Rewrite optimize_circuit method and add InsertStrategy.EARLIEST_AFTER

### PR DESCRIPTION
**Pull request by crystalzhaizhai**
This is supposed to fix PointOptimizer putting in too many moments #2553

### CODE REVIEW

**Comment by balopat** [comment]
Hi @crystalzhaizhai thanks for opening this - the first thing would be to verify your ideas is to make the existing tests pass - and not by modifying the tests (unless absolutely necessary!) but by ensuring that the new logic is backwards compatible. The fact that there are 119 tests failing tells me that this is not backwards compatible behavior yet.

**Comment by crystalzhaizhai** [comment]
> Hi @crystalzhaizhai thanks for opening this - the first thing would be to verify your ideas is to make the existing tests pass - and not by modifying the tests (unless absolutely necessary!) but by ensuring that the new logic is backwards compatible. The fact that there are 119 tests failing tells me that this is not backwards compatible behavior yet.

I spent a few hours to write the prototype to discuss the idea. Will fix the tests for sure!

**Comment by crystalzhaizhai** [comment]
@balopat 
Actually the 38 tests failing in the changed files test are related to the methods I deleted. So I am not too worried.

**Comment by balopat** [comment]
Hi @crystalzhaizhai are you planning to work on this? We would need to fix up the tests first.

**Comment by vtomole** [comment]
I'm closing this as stale. What this PR is meant to fix will be [fixed in the future](https://github.com/quantumlib/Cirq/issues/2553#issuecomment-970564009) by @tanujkhattar

**Pull request closed without merging**
