### PR TITLE
adding install command to asv.conf.json

### PR DESCRIPTION
**Pull request by dkothari11**

### CODE REVIEW

**Comment by vtomole** [comment]
@dkothari11 

Congrats on your first pull request to Cirq! Please provide more context about what this pull request does, namely: what used to break that this fixes?

**Comment by vtomole** [comment]
> pre installed version of cirq would give us more detailed and accurate information about the regression across commits.

How so?  The current way we are doing things still runs the benchmarks off the master branch.

**Review by vtomole — COMMENTED** [review]
I'm trying to figure out if this is necessary.  asv documentation says that we shouldn't need the `install_command` unless we want to benchmark against  multiple versions of third-party dependencies or if our package needs nonstandard installation commands and none of those apply here.

**Comment by vtomole** [comment]
Ping @dkothari11

**Comment by dstrain115** [comment]
@dkothari11 This seems like a stale PR.  As per vtomole, it seems like it would be unneccessary.

Also pinging @tanujkhattar for questions about ASV.  Can we close this PR?

**Comment by tanujkhattar** [comment]
Yes, I think we can close this

**Pull request closed without merging**
