### PR TITLE
Sort PauliString items in __format__ so that it's less brittle

### PR DESCRIPTION
**Pull request by tonybruguier**
It seems we should have a more stable representation, so sorting the keys.

### CODE REVIEW

**Comment by balopat** [comment]
Can you talk to where this brittleness shows up?

**Comment by tonybruguier** [comment]
While working on #3989, I noticed that my unit test expected values had a strange ordering of the Pauli outputs. 

I suspect that it's due to Sympy that parses Boolean expressions in a certain way. If that way were to change in subsequent versions of Sympy, my unit test would fail. (I ran the unit test 100 times and it doesn't seem flaky). 

I could, of course, make my test in #3989 less brittle, but it seemed to me that the PauliSums themselves should be order-independent, so I sent this separate PR. It's a weak preference.

**Comment by balopat** [comment]
> While working on #3989, I noticed that my unit test expected values had a strange ordering of the Pauli outputs.
> 
> I suspect that it's due to Sympy that parses Boolean expressions in a certain way. If that way were to change in subsequent versions of Sympy, my unit test would fail. (I ran the unit test 100 times and it doesn't seem flaky).
> 
> I could, of course, make my test in #3989 less brittle, but it seemed to me that the PauliSums themselves should be order-independent, so I sent this separate PR. It's a weak preference.


I see - I'm not sure I agree - aren't the keys in insertion order, i.e. they keep the order of operations? Would this sorting lead to surprises for a regular PauliSum user? 

If we change this it is technically a breaking change as `str` now will return a different order, so we'll have to mark this PR as such.

**Comment by tonybruguier** [comment]
Sounds good. I am withdrawing this PR and updated PR#3989 instead.

**Pull request closed without merging**
