### PR TITLE
Added `MSGate` to top level

### LINKED ISSUE #6354: MSGate not in top level
**Description of the issue**

`cirq.MSGate` does not exist, but `cirq.ops.MSGate` does.  Think it should be at the top level too?

### PR DESCRIPTION
**Pull request by prakharb10**
Closes #6354 

~The JSON serializability test fails due to `cirq_ionq.ionq_native_gates.MSGate`. I don't know how to resolve this.~

---
~There is also a reference to the gate here:~ https://github.com/quantumlib/Cirq/blob/6e38a2741a0710542baa202ce57acb896eb469a7/cirq-core/cirq/ops/gate_operation_test.py#L511

~Are any changes required?~

### CODE REVIEW

**Comment by pavoljuhas** [comment]
cirq csynque meeting - there is a name conflict with ionq gate which shows in json serialization.
recommendation - mark cirq.MSGate as not-yet-seriazable.

**Comment by pavoljuhas** [comment]
@tanujkhattar - should we support JSON serialization now?  If so, that should be doable by adding `_json_namespace_` class method so we can distinguish between cirq.MSGate and cirq_ionq.MSGate.

If we don't want serialization we should make `cirq.to_json(cirq.ms(1))` fail with ValueError in a similar way as LinearDict [here](https://github.com/quantumlib/Cirq/blob/eef7c5c9309fcdb9254a295491facee3118c2279/cirq-core/cirq/value/linear_dict.py#L312) so we don't produce unusable JSON.

On a second look, adding serialization support seems better, because it is a bit strange to support MSGate in the cirq-ionq extension, but not in cirq-core.

**Comment by tanujkhattar** [comment]
It'll probably be backwards incompatible, which is a bummer. But we don't have backwards compatibility guarantees for vendor packages so we can break users if we want

**Comment by pavoljuhas** [comment]
> It'll probably be backwards incompatible, which is a bummer. But we don't have backwards compatibility guarantees for vendor packages so we can break users if we want

As it is, the round trip `cirq.read_json(json_text=cirq.to_json(cirq.ms(1)))` does not work in the main branch.
It either fails with ValueError because `"MSGate"` type is unknown, or - after importing cirq_ionq - with TypeError, because `cirq_ionq.MSGate` has different arguments.  

What I suggest is to define `cirq.MSGate._json_namespace_` returning `"cirq"`.  That will distinguish the 2 gate types and would be backwards compatible, because cirq.MSGate serialization does not work anyway.

**Review by pavoljuhas — DISMISSED** [review]
After a bit of offline discussion it seems better to support JSON serialization here.
As it is we can serialize `cirq_ionq.MSGate` so for completeness
we should also handle the core cirq.MSGate.

The name conflict can be avoided by defining the `_json_namespace_` class method for `cirq.MSGate`; here is an [example in cirq-google](https://github.com/quantumlib/Cirq/blob/e7bad1f542d595c1086c44239624e1afa24d0452/cirq-google/cirq_google/devices/grid_device.py#L645-L647).

I suggest to use the `"cirq"` namespace for the `cirq.MSGate`.

**Comment by pavoljuhas** [comment]
@prakharb10 - are you available to add serialization support for the cirq.MSGate here?

Feel free to let me know if you are too busy and I can take over from here.

**Comment by prakharb10** [comment]
Hi @pavoljuhas 
I tried adding serialization, but some other tests were failing. I was busy, but I will push the commit with the changes by tomorrow so that you can look at the failing tests.

**Comment by pavoljuhas** [comment]
@tanujkhattar - can you please take a quick look?

**Review by tanujkhattar — APPROVED** [review]

**Pull request merged**
