### PR TITLE
GateFamily: add tags to str representation

### PR DESCRIPTION
**Pull request by verult**
@tanujkhattar

### CODE REVIEW

**Review by dstrain115 — COMMENTED** [review]
Add tests for this.  Otherwise, looks fine to me.

**Comment by verult** [comment]
The default description change broken the JSON serialization test because the old description was captured in `GateFamily.json` for examples with tags set, and the repr of the deserialized object doesn't match what's in `GateFamily.repr` because of these lines:

https://github.com/quantumlib/Cirq/blob/c0c0e5f2e325000b9d3f35cb4d58f33bc6c6d2e9/cirq-core/cirq/ops/gateset.py#L223-L224

The old description no longer matches the new default description, so the repr contains a non-empty description, creating a conflict.

My proposed fix is to leave name and description empty in the JSON if they match the default, just like what we do for repr. IMO repr and json serialization logic should be similar ideally, and if the default name and description are used, there's no value in storing the full name and description anyway. As part of making this change, I also modified the existing objects in `GateFamily.json` and created inward files to make sure the original objects still deserialize properly (albeit to different objects from before).

**Comment by verult** [comment]
Oof, to fix the presubmit failure, there's a bunch of GateFamilies in `GridDeviceMetadata.json` that also would need an `_inward` file. @dstrain115 @tanujkhattar I'll make that fix after you confirm the description serialization approach looks good.

**Comment by verult** [comment]
Discussed with @tanujkhattar offline. Opted to go with the solution which causes the least breakages to unblock the PR, which is to keep the logic the same and fix the description in `GateFamily.json` instead.

**Review by tanujkhattar — APPROVED** [review]
Looks great!

**Pull request merged**
