### PR TITLE
Use parallel pytest in the CI checks

### PR DESCRIPTION
**Pull request by pavoljuhas**
Allow parallel execution of check/pytest scripts in GitHub CI workflows.

### CODE REVIEW

**Comment by pavoljuhas** [comment]
WIP - let's first see if CI tests pass.
cc: @MichaelBroughton

**Comment by pavoljuhas** [comment]
Here is the [current timing](https://github.com/quantumlib/Cirq/runs/5255024345?check_suite_focus=true) of the affected CI jobs compared to the baseline commit; all times are in seconds.  I did not include the *Changed files test*, because number of executed tests can be completely different.  The times are likely subject to the node selection and node load on the GH side, that said we can expect about 5 min shortening of test times (e.g., for Coverage 18m 37s --> 13m 45s).

| CI job | master at 59b72a1ee5ee7c7bec79ad39ef7253f6987bcb16 | PR at fbafc1d66bc75255bbc943a88b60d59260120c3e | delta (s) |
| --- | --- | --- | --- |
| Coverage check | 1117 | 825 | -292 |
| Pytest Ubuntu 3.9 | 587 | 465 | -122 |
| Pytest Windows 3.9 | 874 | 554 | -320 |
| Pytest MacOS | 821 | 392 | -429 |

**Review by MichaelBroughton — COMMENTED** [review]
This looks great. Would you mind periodically checking in on this PR and updating it to the latest master with the "Update Branch" functionality just to make sure it's stable and then we can merge ?

**Comment by pavoljuhas** [comment]
Sure, I will keep this updated.

**Review by MichaelBroughton — APPROVED** [review]
LGTM

**Pull request merged**
