### PR TITLE
Fix deprecated_submodule conflict with importlib_metadata

### PR DESCRIPTION
**Pull request by pavoljuhas**
Stop replacing the entire `sys.meta_path` on every use of `deprecated_submodule`
as this may result in multiple-wrap of standard module finders and finders defined by others.
Add a new finder for our renamed module instead, and use a standard import mechanism to
find it under the new module name.
Remove `find_distributions()` and `invalidate_caches()` methods from DeprecatedModuleFinder,
it should be sufficient to only handle these with standard finders and the new module name.
Add test for the conflict with importlib_metadata.distributions() reported in #4729.

This fixes https://github.com/quantumlib/Cirq/issues/4729.

### CODE REVIEW

**Comment by MichaelBroughton** [comment]
@vtomole Do you have any familiarity with this section of the code ? This seems like a reasonable change to me, but wanted to double check since I saw you had originally put in #4467

**Comment by vtomole** [comment]
From a glance, this seems fine to me as well. The problem that my PR fixed was that Cirq was wrapping the finders and this PR gets rid of the wrapping functionality entirely. Will review in detail by EOD.

**Review by vtomole — COMMENTED** [review]
LGTM. since we're not mocking sphinx anymore , let's remove the stub that ignores it's missing imports: https://github.com/quantumlib/Cirq/blob/4201daa3229c6fa86e66f0c4ef2dbf68e7e38be4/dev_tools/conf/mypy.ini#L32

**Comment by pavoljuhas** [comment]
> since we're not mocking sphinx anymore , let's remove the stub that ignores it's missing imports

Done.  I have also cleaned MockModule, which was only used in a removed test.

**Review by vtomole — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
