### PR TITLE
Document CIRCUIT_TYPE and hide other typevars/aliases in circuits.py

### LINKED ISSUE #5150: Fix docstrings for type aliases in cirq.circuits.circuit.py
**Description of the issue**
The docstrings for type aliases defined in `cirq.circuits.circuit.py` are not helpful and should be improved / fixed. 

For example:
See https://quantumai.google/reference/python/cirq/circuits/circuit#CIRCUIT_TYPE

Where does the line "[INT_TYPE](https://quantumai.google/reference/python/cirq/circuits/circuit/INT_TYPE): The central part of internal API." comes from? 

The reference pages docstring also looks unrelated to the actual type.

https://quantumai.google/reference/python/cirq/circuits/circuit/INT_TYPE

**Cirq version**
0.15dev

### PR DESCRIPTION
**Pull request by maffoo**
Fixes #5150 (assuming this renders nicely on the docsite; how can I check that locally?)

This adds an underscore prefix to hide some type aliases and type vars that are not part of the public interface of the module. Also adds a docstring to the `CIRCUIT_TYPE` variable, which is used in a few other places.

### CODE REVIEW

**Comment by dabacon** [comment]
image
is how it renders now

**Comment by dabacon** [comment]
I think you want to use the document function in _doc.py to get the doc string to render correctly

**Comment by dabacon** [comment]
To get ride of the TYPE_CHECKING it may be possible to filter it out in dev_tools/docs/build_api_docs.py

**Comment by maffoo** [comment]
Filed #5231 about TYPE_CHECKING.

**Review by tanujkhattar — APPROVED** [review]
LGTM. I'll leave a comment on the linked issue to verify this is fixed after the nightly release, before marking it as closed.

**Comment by tonybruguier** [comment]
> Filed #5231 about TYPE_CHECKING.

Would something like #5261 be a reasonable fix?

**Pull request merged**
