### PR TITLE
Add a copyright checker as a pylint plugin

### PR DESCRIPTION
**Pull request by yjt98765**
This PR implements a pylint checker that automatically checks the copyright notice at the beginning of a python file. This task is proposed in [Issue 4564](https://github.com/quantumlib/Cirq/issues/4564).

The PR consists of the following parts:
1. The implemented pylint checker (dev_tools/pylint_copyright_checker.py) and its test file (dev_tools/pylint_copyright_checker_test.py). The checker reports a message with id "R0001" if there is no copyright notice or the notice does not conform to the standard one. The letter 'R' represents refactoring. The checking can be disabled in the file with pragma `# pylint: disable=wrong-copyright-notice`
2. Modification of pylint-related files (check/pylint, check/pylint-changed-files, dev_tools/conf/.pylintrc) to integrate the new checker into the workflow.
3. Python files that failed in this check. Some copyright notices were wrong (e.g. cirq-core/cirq/circuits/circuit_dag.py and cirq-core/cirq/ops/qubit_order_test.py), and they are corrected. Some files did not have a copyright notice. In this case, the "disable" pragma is added. Note that not all the files need to have a copyright notice, [probably](https://softwareengineering.stackexchange.com/a/19653/322605). After the modification, these files can pass pylint checking again.

### CODE REVIEW

**Review by MichaelBroughton — DISMISSED** [review]
Thanks so much for opening this! This is a good looking change. Few high level comments.

**Comment by vtomole** [comment]
Let's have `pylint: disable=wrong-or-nonexistent-copyright-notice` if that's not too long.

**Review by vtomole — COMMENTED** [review]
@yjt98765 Please sign the CLA so we can merge this.

**Comment by yjt98765** [comment]
> @yjt98765 Please sign the CLA so we can merge this.

I have signed it. See the conversation with google-cla (bot) earlier in this thread and also the `cla:yes` label. I do not why the cla process is stuck.

**Comment by vtomole** [comment]
@yjt98765 Will https://stackoverflow.com/a/58190576/5716192 work?

**Comment by yjt98765** [comment]
> @yjt98765 Will https://stackoverflow.com/a/58190576/5716192 work?

Thanks. It triggers the CI, and the cla check passed!

**Comment by vtomole** [comment]
@yjt98765 Merged. Thanks for your patience!

**Pull request merged**
