### PR TITLE
Make Duration JSON serializable

### PR DESCRIPTION
**Pull request by kevinsung**

### CODE REVIEW

**Comment by kevinsung** [comment]
Forgot to add test...

**Comment by kevinsung** [comment]
Ok test added. The format script insisted on a bunch of changes too.

**Comment by mpharrigan** [comment]
Please also remove `"Duration"` from `protocols.json_test.NOT_YET_SERIALIZABLE` and add an entry to `TEST_OBJECTS`. This will plumb it in to the automatic round-trip testing of all serializable objects

**Comment by kevinsung** [comment]
Done.

**Pull request merged**
