### PR TITLE
Batch circuit submit in cirq_ionq

### PR DESCRIPTION
**Pull request by radumarg**
Enable batch circuit job submit in cirq_ionq

### CODE REVIEW

**Comment by pavoljuhas** [comment]
@radumarg , @spich - thank you for the reminder at today's csynque meeting.

Please resolve conflicts with the main branch and the CI-reported issues, then ping me so I can review ASAP.

**Comment by radumarg** [comment]
@pavoljuhas merge conflicts have been fixed

**Comment by radumarg** [comment]
@pavoljuhas Thanks for merging this. I fixed the merge issues but the CI issues indicated a bug in implementation, so I am still working on fixing it and extending unit tests.

**Comment by radumarg** [comment]
@pavoljuhas   The CI issues were fixed. A bug was fixed, tests have been updated. This ticket is ready for review.

**Review by pavoljuhas — APPROVED** [review]
Thank you for contributing this!

**Pull request merged**
