### PR TITLE
Deprecate optimize_for_sycamore and optimize_for_xmon

### PR DESCRIPTION
**Pull request by verult**
* Added deprecation warnings
* Updated tests to check for deprecation warnings.
@tanujkhattar @MichaelBroughton

### CODE REVIEW

**Review by MichaelBroughton — APPROVED** [review]
LGTM

**Comment by tanujkhattar** [comment]
@verult Ideally, we need to create google-specific versions of cz and sqrt-iswap target gatesets, which correctly handle wait gates and have additional postprocess transformers like `eject_z` and `eject_phased_paulis`. 


It would be good to evaluate whether the proposed fix (i.e. using `cirq.optimize_for_target_gateset` with cirq-core gatesets) will be end up breaking the users flow who depend upon `cg.optimized_for_sycamore` or not. One way to evaluate this would be to rewrite the existing tests of `cg.optimized_for_sycamore` using `cirq.optimize_for_target_gateset` as well.

**Comment by verult** [comment]
Sounds good. I'm focusing on `SerializableDevice` and `SerializableGateSet` deprecations for the time being (the scope is growing larger than I anticipated). Not sure if I can get to this before the release deadline, but will take a look right after deprecations are done.

**Comment by verult** [comment]
@MichaelBroughton and I chatted about this and we decided to postpone the evaluation until after the 0.15 release.

If tests break, we could perhaps make a patch release to update the deprecation warning.

**Pull request merged**
