### PR TITLE
Fix indentation in docs

### LINKED ISSUE #3729: Inconsistent level of indentation in some notebooks
Sometimes things are indented with two spaces and sometimes with four. Python and Cirq use four. When you open this notebook in jupyter, the syntax highlighting looks very bad for the 2-indent cells

### PR DESCRIPTION
**Pull request by unaiic**
Changes notebooks which used 2 or 3 spaces as indentation. Python and Cirq use 4 instead, thus the level of indentation is made consistent.

Fixes #3729.

### CODE REVIEW

**Comment by vtomole** [comment]
Is it possible to added a format checker like  [Jupyter-black](https://github.com/drillan/jupyter-black). I've filed https://github.com/quantumlib/Cirq/issues/3976

**Comment by 95-martin-orion** [comment]
@unaiic and @vtomole: do the changes linked in #3976 make this obsolete? If so, we should close this PR.

**Comment by vtomole** [comment]
@95-martin-orion Wow. This notification slipped by me. Yes, we can close.

**Comment by mpharrigan** [comment]
Can we merge this anyway? https://github.com/quantumlib/Cirq/pull/4020 is taking a while and this PR is a clear improvement over the status quo.

**Review by mpharrigan — APPROVED** [review]

**Comment by vtomole** [comment]
@mpharrigan I Agree.

**Comment by mpharrigan** [comment]
sweet thanks

**Pull request merged**
