### PR TITLE
Add 'no-else-return' to .pylintrc

### PR DESCRIPTION
**Pull request by vtomole**
Merge after https://github.com/quantumlib/Cirq/pull/1769 and https://github.com/quantumlib/Cirq/pull/1768

### CODE REVIEW

**Comment by Strilanc** [comment]
I'm not sure we should merge this. Do we consider this to be an important part of our style guide?

I think this is an example of enforcing a rule that doesn't *really* matter. Code isn't more error-prone if it has redundant else's, and it won't be more performant... it's just a bit less verbose. Note how all the other lint checks are either about potential mistakes or optimizations.

**Comment by vtomole** [comment]
> it's just a bit less verbose

I think this is good. It's the ultimate `nit` ;)

**Comment by vtomole** [comment]
@Strilanc Will merge or close after a response to my comment.

**Comment by Strilanc** [comment]
We decided at the group meeting to keep linting about possible mistakes, instead of style issues.

**Pull request closed without merging**
