### PR TITLE
Run tests against python 3.10

### PR DESCRIPTION
**Pull request by maffoo**
Test against all the versions.

### CODE REVIEW

**Comment by maffoo** [comment]
Looks like we will need to update the grpc library version to support 3.10.

**Comment by MichaelBroughton** [comment]
Looks like the least intrusive upgrade here is `grpcio-tools~=1.36.0` in `protos.txt`. This would take the bundled protoc to 3.14 from 3.13.0.  Would this interfere with any of the cirq-google gapic or proto stuff @maffoo , @verult , @wcourtney ?

**Comment by verult** [comment]
I'm not aware of any problems with device and program protos. If we can go further and move to 3.15, that'd be even better - optional fields are only supported in >=3.15 and I'd like to make the `gate_duration` field optional if time allows before Cirq 1.0. But this is by no means a strong requirement.

**Comment by maffoo** [comment]
@MichaelBroughton, I don't think bumping the grpcio-tools version will be a problem for cirq-google; we will have to regenerate the proto files, but that's easy, and the gapic code now uses the `proto` library instead of `google.protobuf` so it doesn't care about the protoc version.

@verult, in proto3 _all_ fields are optional by default, so I don't think we need to do anything special to treat `gate_duration` as optional. Do you have any more information about the change in 3.15 that you're interested in?

**Comment by verult** [comment]
The feature I'm looking for is to be able to distinguish between an unset field and a field which is set to the default value of the type. For `gate_duration`, it's to be able to tell whether a gate has 0 duration vs no duration information. But this isn't a strong requirement because `gate_duration` is mostly informational.

See: https://stackoverflow.com/questions/42622015/how-to-define-an-optional-field-in-protobuf-3

**Comment by maffoo** [comment]
Hm, we need to update mypy to get it to install on mac/windows with 3.10, but updating mypy update is not trivial. I'm inclined to disable 3.10 tests for windows and mac for now and do that as a follow-up.

**Comment by MichaelBroughton** [comment]
Why is updating mypy not trivial ?

**Comment by maffoo** [comment]
mypy updated in #5767 so that we can now run 3.10 tests on windows and mac. @MichaelBroughton, PTAL.

**Review by pavoljuhas — APPROVED** [review]
LGTM.

**Review by viathor — APPROVED** [review]
me wants this

(making new cirq virtualenv and grpcio-tools fails to build, hoping this is the fix)

**Review by MichaelBroughton — APPROVED** [review]

**Pull request merged**
