### PR TITLE
Implement decompose_two_qubit_interaction_into_four_fsim_gates_via_b

### PR DESCRIPTION
**Pull request by Strilanc**
This code is not very performant, but it does the job. Any two qubit unitary can be decomposed into four FSIM gates that within 22.5 degrees of maximum iswap and 45 degrees of minimum cphase. The decomposition works by decomposing a B gate into two fsims using a technique by @john6060, and then using https://arxiv.org/abs/quant-ph/0312193 to make anything out of two B gates.

This PR also happens to add default values for some `__init__` parameters of KakDecomposition.

### CODE REVIEW

**Comment by Strilanc** [comment]
Here's the space of fsim gates that this decomposition works for. The iswap angle has to be within 22.5 degrees of maximum strength (pi/2) and the cphase angle has to be within 45 degrees of minimum strength (0).

image

```
    import cirq
    import numpy as np
    import matplotlib.pyplot as plt
    xs = []
    ys = []
    for theta in np.linspace(0, np.pi, 200):
        for phi in np.linspace(-np.pi/2, np.pi/2, 200):
            try:
                _decompose_xx_yy_into_two_fsims_ignoring_single_qubit_ops(
                    qubits=cirq.LineQubit.range(2),
                    fsim_gate=cirq.FSimGate(theta=theta, phi=phi),
                    canonical_x_kak_coefficient=np.pi / 4,
                    canonical_y_kak_coefficient=np.pi / 8,
                )
                xs.append(theta)
                ys.append(phi)
            except ValueError:
                pass

    plt.scatter(xs, ys, s=1)
    plt.xlabel('theta (iswap angle)')
    plt.ylabel('phi (cphase angle)')
    plt.xlim(0, np.pi)
    plt.ylim(-np.pi/2, +np.pi/2)
    xticks = np.linspace(0, np.pi, 5)
    yticks = np.linspace(-np.pi/2, +np.pi/2, 5)
    plt.xticks(xticks, ['0\n(Id)', '0.25π\n(√iswap)', '0.5π\n(iswap)', '0.75π', 'π\n(ZZ)'])
    plt.yticks(yticks, ['(CS†) -0.5π', '-0.25π', '(Id) 0', '0.25π', '(CS) 0.5π'])
    plt.grid()
    plt.show()
```

**Comment by Strilanc** [comment]
All gates that were used in the supremacy paper fall into the feasible regime:

image

Here is a decomposition of SWAP**0.9 using the ideal Sycamore using this technique:

```
0                             1                             global phase:
│                             │
┌                           ┐ ┌                           ┐
│-0.068-0.87j   0.248+0.421j│ │-0.452+0.566j  0.155-0.671j│ -0.608π
│-0.248+0.421j -0.068+0.87j │ │-0.155-0.671j -0.452-0.566j│
└                           ┘ └                           ┘
│                             │
SYC───────────────────────────SYC
│                             │
┌                           ┐ ┌                           ┐
│-0.097-0.739j  0.661+0.087j│ │ 0.9  -0.118j  0.055-0.417j│
│-0.661+0.087j -0.097+0.739j│ │-0.055-0.417j  0.9  +0.118j│
└                           ┘ └                           ┘
│                             │
SYC───────────────────────────SYC
│                             │
┌                           ┐ ┌                           ┐
│ 0.089-0.779j  0.081-0.616j│ │ 0.609-0.727j -0.254-0.191j│
│-0.081-0.616j  0.089+0.779j│ │ 0.254-0.191j  0.609+0.727j│
└                           ┘ └                           ┘
│                             │
SYC───────────────────────────SYC
│                             │
┌                           ┐ ┌                           ┐
│-0.097-0.739j  0.661+0.087j│ │ 0.9  -0.118j  0.055-0.417j│
│-0.661+0.087j -0.097+0.739j│ │-0.055-0.417j  0.9  +0.118j│
└                           ┘ └                           ┘
│                             │
SYC───────────────────────────SYC
│                             │
┌                           ┐ ┌                           ┐
│ 0.858+0.215j  0.225+0.409j│ │ 0.205+0.538j -0.76 +0.301j│
│-0.225+0.409j  0.858-0.215j│ │ 0.76 +0.301j  0.205-0.538j│
└                           ┘ └                           ┘
│                             │
```

**Comment by mpharrigan** [comment]
gorgeous!

**Comment by Strilanc** [comment]
Note sure why the decomposition is producing so many NaNs during the windows tests but no others...

**Comment by dabacon** [comment]
Nice!

**Pull request merged**
