### PR TITLE
Update pylint version from 2.1.* to 2.3.* and remove "unnecessary pass" warnings.

### PR DESCRIPTION
**Pull request by vtomole**

### CODE REVIEW

**Comment by Strilanc** [comment]
What is up with travis-ci lately? Random double-notifications, this one hanging forever...

**Comment by Strilanc** [comment]
Restarting one of the jobs seems to have triggered it to actually send the status completion.

**Comment by verult** [comment]
Seeing the error below in Travis install step:

pylint 2.3.1 has requirement astroid<3,>=2.2.0, but you'll have astroid 2.1.0 which is incompatible.

Should astroid version be bumped too?

**Comment by Strilanc** [comment]
I suspect that will trigger the parsing bug. Kind of surprised pylint managed to work with an older version.

**Comment by vtomole** [comment]
@verult Bumping it will break pylint. I'm not seeing that "incompatible" warning on Travis builds. Where is it?

**Comment by vtomole** [comment]
This appears when `check.sh` is run. I vote for leaving it until that astroid bug is fixed but i'm willing to revert if people think differently.

**Comment by verult** [comment]
I'm seeing it here:
https://travis-ci.com/quantumlib/Cirq/jobs/193471026#L752
I'm surprised the install is shown as succeeding in the end, but hey as long as tests pass :)

OK with leaving as is too

**Pull request merged**
