### PR TITLE
Bump up cirq requirements to protobuf 4.x

### LINKED ISSUE #5929: Incompatible versions in Cirq 1.0.0
**Description of the issue**
Protobuf versions of various transient dependencies do no match for Cirq 1.0.0. For those of us who prefer to peg versions, this represents a problem.

**How to reproduce the issue**

1. Create reqs.in file with `cirq==1.0.0` as its contents
2. Run `pip-compile reqs.in`
3. Check output:

```
Could not find a version that matches protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<4,<4.0.0dev,<5.0.0dev,>=3.15.0,>=3.19.0,>=3.19.5,>=4.21.6 (from cirq-google==1.0.0->cirq==1.0.0->-r reqs.in (line 1))
Tried: 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0, 3.0.0, 3.1.0, 3.1.0.post1, 3.1.0.post1, 3.2.0, 3.2.0, 3.3.0, 3.4.0, 3.4.0, 3.5.0.post1, 3.5.0.post1, 3.5.1, 3.5.1, 3.5.2, 3.5.2, 3.5.2.post1, 3.5.2.post1, 3.6.0, 3.6.0, 3.6.1, 3.6.1, 3.7.0, 3.7.0, 3.7.1, 3.7.1, 3.8.0, 3.8.0, 3.9.0, 3.9.0, 3.9.1, 3.9.1, 3.9.2, 3.9.2, 3.10.0, 3.10.0, 3.11.0, 3.11.0, 3.11.1, 3.11.1, 3.11.2, 3.11.2, 3.11.3, 3.11.3, 3.12.2, 3.12.2, 3.12.4, 3.12.4, 3.13.0, 3.13.0, 3.14.0, 3.14.0, 3.15.0, 3.15.0, 3.15.1, 3.15.1, 3.15.2, 3.15.2, 3.15.3, 3.15.3, 3.15.4, 3.15.4, 3.15.5, 3.15.5, 3.15.6, 3.15.6, 3.15.7, 3.15.7, 3.15.8, 3.15.8, 3.16.0, 3.16.0, 3.17.0, 3.17.0, 3.17.1, 3.17.1, 3.17.2, 3.17.2, 3.17.3, 3.17.3, 3.18.0, 3.18.0, 3.18.1, 3.18.1, 3.18.3, 3.18.3, 3.19.0, 3.19.0, 3.19.1, 3.19.1, 3.19.2, 3.19.2, 3.19.3, 3.19.3, 3.19.4, 3.19.4, 3.19.5, 3.19.5, 3.19.6, 3.19.6, 3.20.0, 3.20.0, 3.20.1, 3.20.1, 3.20.2, 3.20.2, 3.20.3, 3.20.3, 4.21.0, 4.21.0, 4.21.0, 4.21.0, 4.21.1, 4.21.1, 4.21.1, 4.21.1, 4.21.2, 4.21.2, 4.21.2, 4.21.2, 4.21.3, 4.21.3, 4.21.3, 4.21.3, 4.21.4, 4.21.4, 4.21.4, 4.21.4, 4.21.5, 4.21.5, 4.21.5, 4.21.5, 4.21.6, 4.21.6, 4.21.6, 4.21.6, 4.21.7, 4.21.7, 4.21.7, 4.21.7, 4.21.8, 4.21.8, 4.21.8, 4.21.8
Skipped pre-versions: 2.0.0b0, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0b4, 3.2.0rc1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0rc2, 3.7.0rc2, 3.7.0rc2, 3.7.0rc3, 3.7.0rc3, 3.8.0rc1, 3.8.0rc1, 3.9.0rc1, 3.9.0rc1, 3.10.0rc1, 3.10.0rc1, 3.11.0rc1, 3.11.0rc1, 3.11.0rc2, 3.11.0rc2, 3.13.0rc3, 3.13.0rc3, 3.14.0rc1, 3.14.0rc1, 3.14.0rc2, 3.14.0rc2, 3.14.0rc3, 3.14.0rc3, 3.15.0rc1, 3.15.0rc1, 3.15.0rc2, 3.15.0rc2, 3.16.0rc1, 3.16.0rc1, 3.16.0rc2, 3.16.0rc2, 3.17.0rc1, 3.17.0rc1, 3.17.0rc2, 3.17.0rc2, 3.18.0rc1, 3.18.0rc1, 3.18.0rc2, 3.18.0rc2, 3.19.0rc1, 3.19.0rc1, 3.19.0rc2, 3.19.0rc2, 3.20.0rc1, 3.20.0rc1, 3.20.0rc2, 3.20.0rc2, 3.20.1rc1, 3.20.1rc1, 4.0.0rc1, 4.0.0rc1, 4.0.0rc2, 4.0.0rc2, 4.21.0rc1, 4.21.0rc1, 4.21.0rc1, 4.21.0rc1, 4.21.0rc2, 4.21.0rc2, 4.21.0rc2, 4.21.0rc2
There are incompatible versions in the resolved dependencies:
  protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<4.0.0dev,>=3.19.5 (from google-api-core[grpc]==1.33.2->cirq-google==1.0.0->cirq==1.0.0->-r reqs.in (line 1))
  protobuf<4,>=3.15.0 (from cirq-google==1.0.0->cirq==1.0.0->-r reqs.in (line 1))
  protobuf<5.0.0dev,>=3.19.0 (from proto-plus==1.22.1->cirq-google==1.0.0->cirq==1.0.0->-r reqs.in (line 1))
  protobuf<5.0.0dev,>=3.15.0 (from googleapis-common-protos==1.56.4->google-api-core[grpc]==1.33.2->cirq-google==1.0.0->cirq==1.0.0->-r reqs.in (line 1))
  protobuf>=4.21.6 (from grpcio-status==1.50.0->google-api-core[grpc]==1.33.2->cirq-google==1.0.0->cirq==1.0.0->-r reqs.in (line 1))
```

**Cirq version**
1.0.0

### PR DESCRIPTION
**Pull request by pavoljuhas**
- Bump up to dependencies to protobuf 4.x
- Rebuild proto-derived sources to reflect protobuf 4.x
- Update expected textproto for protobuf 4.x
- fix new mypy complaints about proto-derived types

Fixes #5929

### CODE REVIEW

**Comment by pavoljuhas** [comment]
This fix has a slight downside that any other packages using both cirq and protobuf would need to upgrade to protobuf 4.x.
I feel that that transition would need to happen at some point anyway.

Do we want to add CI check for successful pip-compile?

**Comment by pavoljuhas** [comment]
@tanujkhattar , @mpharrigan - can you PTAL?

**Review by mpharrigan — APPROVED** [review]
I don't know anything about the backwards-compatibility implications of the changes to the generated pb2.py files, but LGTM

**Comment by pavoljuhas** [comment]
> I don't know anything about the backwards-compatibility implications of the changes to the generated pb2.py files, but LGTM

I have skimmed through the Python notes in https://github.com/protocolbuffers/protobuf/blob/main/CHANGES.txt and could not see Python API changes likely to impact us.  As for the serialized content, that should be backwards compatible.  I had to update the expected textproto for a test in 4aa01461ce5551299b89a950f9009fd09b5d0826, but all changes were in the output order or in dropping the decimal point for integer floats, e.g., `0.0` --> `0`.

**Comment by pavoljuhas** [comment]
cc @maffoo - in case there might be some serious implications for updating protobuf in pyle.  We would like to continue installing cirq and pyle in the same virtual environment, so if one bumps up the protobuf requirement, it affects the other  as well.

**Comment by maffoo** [comment]
Usually protobuf updates are fairly easy in pyle, but I'm guessing 3->4 will cause more headaches than usual. Probably just gonna have to try it out though, and see if anything breaks. One possible issue would be if other dependencies want protobuf 3 (e.g. something like tensorflow).

**Comment by tanujkhattar** [comment]
I think TFQ is probably at the highest risk of breaking with this change. See https://github.com/tensorflow/quantum/blob/master/requirements.txt

@MichaelBroughton Do you have thoughts on if / how this might break TFQ ?

**Comment by pavoljuhas** [comment]
Thank you all for the feedback.  The gentler solution seems to be to pin the grpcio-status dependency so it stays compatible with protobuf 3.x and makes pip-compile happy.  Please see #5953.

I am converting this to a draft in case it would help with protobuf 3.x -> 4.x transition sometime in the future.

**Comment by pavoljuhas** [comment]
Superseded by #6191

**Pull request closed without merging**
