### PR TITLE
Make gate_sets actually optional

### PR DESCRIPTION
**Pull request by dstrain115**
- mypy and pycharm need a default value in the abstract interface
in order to be truly optional.
- Also, add a copy of the inherited arguments in
SimulatedLocalProcessor.

### CODE REVIEW

**Review by MichaelBroughton — CHANGES_REQUESTED** [review]
All of the changes here look like dangerous default values. Would it be possible for the optional case to do something like:

```python3
def my_method(some_optional_thing = None):
   if some_optional_thing is None:
    some_optional_thing = promote_to(somethingorother)

```
?

**Comment by dstrain115** [comment]
> All of the changes here look like dangerous default values. Would it be possible for the optional case to do something like:

Changed.

**Comment by mpharrigan** [comment]
what about `get_sampler`

**Comment by mpharrigan** [comment]
oh weird maybe I was looking at only a subset of commits

**Review by mpharrigan — APPROVED** [review]

**Review by MichaelBroughton — APPROVED** [review]

**Pull request merged**
