### PR TITLE
adds TextDiagramDrawer.horizontal_cut

### PR DESCRIPTION
**Pull request by bryano**

### CODE REVIEW

**Comment by Strilanc** [comment]
Needs to be synced with recent changes to text diagram drawer.

**Comment by Strilanc** [comment]
Still needs to be synced with recent changes to text diagram drawer. I will close in two weeks if no activity.

**Comment by bryano** [comment]
@Strilanc It only makes sense to get this up to date if we're going to implement my [proposal](https://github.com/quantumlib/Cirq/issues/1226#issuecomment-445994196) for drawing outline boxes in #1226, of which this was meant to be a first step. I know you had alternative ideas about how to proceed, so let me know.

**Comment by dabacon** [comment]
This seems to have grown stale.  I'm closing.  If it can be salvaged, please open a new PR.

**Pull request closed without merging**
