### PR TITLE
Add atol parameter to wavefunction and density matrix utils

### LINKED ISSUE #2148: to_valid_density_matrix is too picky
The density matrix result of `sim.simulate()` regularly fails the assertions in `to_valid_density_matrix`. I had to weaken the tolerances for my code (which worked just fine under the previous implementation that just didn't check)

cc #1901

### PR DESCRIPTION
**Pull request by kevinsung**
Fixes #2148

### CODE REVIEW

**Comment by mpharrigan** [comment]
Without looking at it too deeply, I found the default of 1e-8 to be too strict in practice for reasonably sized density matrices

**Comment by mpharrigan** [comment]
Can you include this for the trace and hermitian tests as well; I had to loosen all of them for my usage

**Comment by kevinsung** [comment]
Are you using complex64 or complex128 for your density matrices? I'd expect 1e-8 to work for complex128 but not for complex64.

**Comment by mpharrigan** [comment]
I use whatever `cirq.DensityMatrixSimulator()` gives me

**Comment by kevinsung** [comment]
@mpharrigan I've changed the default to 1e-7. Have you found that to be good enough for your applications? I think we should definitely have a default that works with the default settings of the simulators.

**Comment by mpharrigan** [comment]
This seems to work for me with some brief testing

**Pull request merged**
