### PR TITLE
Remove `cirq.Tolerance` in favor of passing `atol` and `rtol` in method parameters.

### PR DESCRIPTION
**Pull request by bbonnet**
Removes the `Tolerance` class in favor for passing `atol` (Absolute Tolerance) and `rtol` (Relative Tolerance) as float method parameters .

Addresses: https://github.com/quantumlib/Cirq/issues/1190

- [x] Remove `Tolerance` from the public API
- [x] Exposes Default `atol` and `rtol` constants internally to avoid setting defaults across the project
- [ ] WIP: Renames `tolerance` method paramters to `atol` and/or `rtol` to explicitly indicate what tolerance type is being set on the API

Hi! It's my first PR here and wanted to tackle this one to get familiar with the codebase.  Hope that this helps!  Looking for earlier feedback before wrapping up some loose ends.

### CODE REVIEW

**Comment by bbonnet** [comment]
Rerun CLA

**Comment by bbonnet** [comment]
Rerun CLA

**Comment by vtomole** [comment]
@bbonnet Thanks for taking this. I recommend running the checks locally as using the travis logs for debugging could be inefficient.

**Comment by bbonnet** [comment]
@vtomole I took a look at your PR however IMO I think it would be best to keep tolerance.py along with the utility methods for the following reasons:

- Prevent copying of logic for the all near zero and all near zero mod methods which are non-obvious.  This also makes it for future functionality to add tolerance by calling these utility methods.
- Keep the unit test coverage on these methods esp. because many of the methods that use the tolerance do not have test coverage across all tolerance settings.  Adding that test coverage at every implementation would probably be over-kill.

The changes in this PR should cover the main spirit of #1190 which is to remove the Tolerance class from the public API however I think the internals still do benefit from these helpers.  Happy to discuss further if you disagree.

**Comment by vtomole** [comment]
@bbonnet  Sounds good.

**Comment by bbonnet** [comment]
@Strilanc @dabacon Thanks for the review! I've updated based on your comments and this should be ready for another look.

**Pull request merged**
