### PR TITLE
Attempt to fix flaky test by fixing random seed in n_qubit_tomography_test.py

### PR DESCRIPTION
**Pull request by tonybruguier-google**
It seems the test can be a bit flaky
https://travis-ci.com/quantumlib/Cirq/jobs/285096296

Happy to modify or outright withdraw if this is misguided.

### CODE REVIEW

**Comment by dstrain115** [comment]
Can you let me know how this affects the speed of the test?  If I recall, I tuned these numbers down in a recent PR in order to speed the tests up.  I guess this made the test flaky as well.  

I just want to make sure that we don't slow things down too much.  

I think the command is 'pytest FILE --durations=20' to output test durations.

**Comment by tonybruguier-google** [comment]
Here it is. I had considered instead loosening the tolerances to 0.10, but this felt like a better test. Not a strong preference at all, though.

```
======================================================================== test session starts =========================================================================
platform linux -- Python 3.7.5rc1, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /google/src/cloud/tonybruguier/git/google3/experimental/users/tonybruguier/git/cirq
collected 11 items                                                                                                                                                   

cirq/experiments/n_qubit_tomography_test.py ...........                                                                                                        [100%]

===================================================================== slowest 20 test durations ======================================================================
6.91s call     cirq/experiments/n_qubit_tomography_test.py::test_density_matrix_from_state_tomography_is_correct[circuit4-qubits4]
1.84s call     cirq/experiments/n_qubit_tomography_test.py::test_density_matrix_from_state_tomography_is_correct[circuit3-qubits3]
1.17s call     cirq/experiments/n_qubit_tomography_test.py::test_agrees_with_two_qubit_state_tomography[circuit0]
1.14s call     cirq/experiments/n_qubit_tomography_test.py::test_agrees_with_two_qubit_state_tomography[circuit1]
1.12s call     cirq/experiments/n_qubit_tomography_test.py::test_agrees_with_two_qubit_state_tomography[circuit2]
0.55s call     cirq/experiments/n_qubit_tomography_test.py::test_density_matrix_from_state_tomography_is_correct[circuit1-qubits1]
0.54s call     cirq/experiments/n_qubit_tomography_test.py::test_density_matrix_from_state_tomography_is_correct[circuit2-qubits2]
0.30s call     cirq/experiments/n_qubit_tomography_test.py::test_state_tomography_diagonal
0.28s call     cirq/experiments/n_qubit_tomography_test.py::test_state_tomography_ghz_state
0.20s call     cirq/experiments/n_qubit_tomography_test.py::test_density_matrix_from_state_tomography_is_correct[circuit0-qubits0]
0.07s call     cirq/experiments/n_qubit_tomography_test.py::test_make_experiment_no_rots

(0.00 durations hidden.  Use -vv to show these durations.)
======================================================================== 11 passed in 14.41s =========================================================================
```

**Comment by dstrain115** [comment]
Yuck.  This adds a fair bit of time to the test.  I am loathe to add several seconds onto everyone's PRs and tests for just this experiment.  I'd personally rather loosen the constraints.  This is just a unit test, not a real experiment.  What do you think?

**Comment by tonybruguier-google** [comment]
Now with looser conditions instead of more repetitions

**Comment by mpharrigan** [comment]
You can also try to make this test deterministic by fixing simulator random seeds

**Comment by dstrain115** [comment]
> You can also try to make this test deterministic by fixing simulator random seeds

Oh yeah!  That's a way better idea.  I would recommend doing that instead.

**Comment by tonybruguier-google** [comment]
Seems indeed like the right way to go. Thanks for the suggestion. Done, I think.

**Pull request merged**
