### PR TITLE
Add tags to MeasureInfo

### PR DESCRIPTION
**Pull request by dstrain115**
- When we call cirq.google.api.v2.find_measurements, we need a way
to retrieve tags that were originally on the circuit.
- This adds tags to the NamedTuple that is returned by this function
that includes tags.

This does change the output of this function, but, since it is an
additive change, it should be minimally breaking.

### CODE REVIEW

**Review by balopat — APPROVED** [review]
LGTM

**Comment by balopat** [comment]
> since it is an additive change, it should be minimally breaking.
I think so too, especially that `NamedTuple`s cannot be unpacked (e.g. `a,b,c,d = v2.MeasurementInfo` is invalid), users have to rely on field, thus old code will work with the new MeasurementInfo.

**Comment by maffoo** [comment]
@balopat, `NamedTuple` actually _can_ be unpacked (it's just a typed wrapper around [`collections.namedtuple`](https://docs.python.org/3/library/collections.html#collections.namedtuple). I'd actually suggest changing this to be a `dataclasses.dataclass`.

**Comment by mpharrigan** [comment]
+1 use dataclasses wherever you're inclined to use namedtuples

**Comment by dstrain115** [comment]
SGTM, I don't like NamedTuples anyway.  Changed to a dataclass.
This should only be as breaking as the original PR as long as people aren't doing any inspection of the internals of the class, it should be fine.  Also, it is in cirq.google.

**Comment by balopat** [comment]
> @balopat, `NamedTuple` actually _can_ be unpacked (it's just a typed wrapper around [`collections.namedtuple`](https://docs.python.org/3/library/collections.html#collections.namedtuple)). I'd actually suggest changing this to be a `dataclasses.dataclass`.

Huh, they really can, I must have overlooked something and made a mistake when I tried it out. TIL!

**Comment by balopat** [comment]
I added the BREAKING_CHANGE label for warning in the release notes.

**Pull request merged**
