### PR TITLE
Make string for powered gates consistent

### PR DESCRIPTION
**Pull request by dabacon**
Changes `__str__` for `HPowGate` and `PhasedXPowGate` to be consistent with other methods that can be powered and uses `**` and not `^` for the powering, i.e. `H**0.5` not `H^0.5`.

### CODE REVIEW

**Comment by dabacon** [comment]
Not sure why the formatter went so crazy, yapf really seems to format multiline dicts pretty poorly.

**Comment by maffoo** [comment]
Re: formatting, see https://github.com/quantumlib/Cirq/pull/3516 :-)

**Review by viathor — APPROVED** [review]

**Comment by dabacon** [comment]
> Re: formatting, see #3516 :-)

I saw that!  Black seems to format the dicts nicely, whereas yapf makes the sound yapf when it formats them.

**Review by balopat — APPROVED** [review]

**Comment by balopat** [comment]
Uh-oh, out-of-time-order commits :) 
```
E           AssertionError: Pattern 'H\\^0.5' does not match 'Gate H**0.5 acting on [0] cannot be serialized by IonQ API.'
```

**Comment by dabacon** [comment]
Stop hitting yourself @dabacon

**Pull request merged**
