### PR TITLE
Delete continuous-integration/check.sh and simple_check.sh

### PR DESCRIPTION
**Pull request by Strilanc**
- These have fallen out of sync with how the build is run on travis, and are slower than the stuff under check/
- Also remove files that only existed to make these two scripts work

@dabacon I know you still sometimes use these scripts. What do you think?

### CODE REVIEW

**Comment by dabacon** [comment]
I still use them yeah.  What should I do instead?

**Comment by vtomole** [comment]
How are these programs different from a script that runs `check/mypy, format, pylint e.t.c at once?"

**Comment by Strilanc** [comment]
These scripts set up entire virtual envs and run the checks in those virtual envs. That's the main difference.

Dave, I personally just use the individual scripts in `check/`.

**Comment by vtomole** [comment]
> set up entire virtual envs and run the checks in those virtual envs

So travis-like locally? Have there been instances where `check/` missed something then travis failed but it would have been caught by `check.sh`?

**Comment by Strilanc** [comment]
Yes, when e.g. we didn't pin the version of pylint.

There's also been the opposite, due to e.g. check.sh not including the format check. Nothing is actually verifying that this script continues to work.

**Comment by Strilanc** [comment]
Got some pushback so it'll stay... *for now*

**Pull request closed without merging**
