### PR TITLE
Observable Measurement - 4 - Sampling Loop

### PR DESCRIPTION
**Pull request by mpharrigan**
- Full prototype #2781
  - Settings #3371 
  - Grouping #3372 
  - Data #3374 
  - Correction #3649 
  - Sampling **this** (split)
    - Pre-reqs #3792 
    - Loop #3855 
    - Stopping #3969 
    - Readout #4323 
    - Checkpointing #4352 
    - High-level API #4392 
  - Top level imports (todo)
  - Examples (todo)

Follows #3374 

Part of #2781

### CODE REVIEW

**Comment by balopat** [comment]
Is this ready for review @mpharrigan?

**Comment by mpharrigan** [comment]
This PR had most of its parts split up into smaller PRs. There's still a couple more I need to polish up to finish it. I updated the top comment to show the full structure.

**Comment by balopat** [comment]
> This PR had most of its parts split up into smaller PRs. There's still a couple more I need to polish up to finish it. I updated the top comment to show the full structure.

Thanks that looks great! cc @95-martin-orion who is interested in this because of the expectation value api.

**Comment by dabacon** [comment]
@mpharrigan does this still need to be an open PR?  Is there stuff left that has not been implemented?

**Comment by mpharrigan** [comment]
I still have some examples in my local fork but we can close this

**Pull request closed without merging**
