### PR TITLE
Fix _compat tests

### PR DESCRIPTION
**Pull request by dabacon**
Fixes some of the out of order test breakage described in #4921 

These tests are certainly broken, they are supposed to pass in the function not the result of the function.

Not sure I fully see why this interacts badly with test_deprecated_module tests, but once it hits one of these failing the following parameterized tests fail.

### CODE REVIEW

**Comment by dabacon** [comment]
Oh wait not quite fixed correctly yet.

**Comment by pavoljuhas** [comment]
> Not sure I fully see why this interacts badly with test_deprecated_module tests, but once it hits one of these failing the following parameterized tests fail.

The functions were supposed to run in a subprocess so they do their imports in isolation.
The original code executed imports in the main thread affecting import warnings for others.

BTW, I also saw a missing import error, please add

```diff
diff --git a/cirq-core/cirq/_compat_test.py b/cirq-core/cirq/_compat_test.py
index 1dd95bb2..28dfb6dd 100644
--- a/cirq-core/cirq/_compat_test.py
+++ b/cirq-core/cirq/_compat_test.py
@@ -798,6 +798,8 @@ def _test_broken_module_2_inner():
 
 
 def _test_broken_module_3_inner():
+    import cirq.testing._compat_test_data
+
     with cirq.testing.assert_deprecated(deadline="v0.20", count=None):
         with pytest.raises(
             DeprecatedModuleImportError,
```

**Comment by dabacon** [comment]
OK, yeah patched things up.  Yeah these tests were no-ops, so nice to fix.

**Comment by dabacon** [comment]
Also added an assert to make sure none of the other cases were failing in this manner.

**Comment by dabacon** [comment]
Ah now windows tests are failing.  Joy.

**Comment by pavoljuhas** [comment]
Tests may be failing on Windows because they use `spawn` rather than `fork` to start multiprocessing jobs.
I got some test failures on Linux after hardcoding `spawn` at that line - https://github.com/quantumlib/Cirq/blob/4f354ea6fce895c16e962697fb923a7d61c1f818/cirq-core/cirq/_compat_test.py#L603

This seems to get fixed after explicitly activating Python warnings in the failing tests.
Please check if the following patch would help - [0001-Activate-warnings-for-multiprocessing-spawn-context.patch.txt](https://github.com/quantumlib/Cirq/files/7983191/0001-Activate-warnings-for-multiprocessing-spawn-context.patch.txt)

```diff
diff --git a/cirq-core/cirq/_compat_test.py b/cirq-core/cirq/_compat_test.py
index 28dfb6dd..e6ab64e3 100644
--- a/cirq-core/cirq/_compat_test.py
+++ b/cirq-core/cirq/_compat_test.py
@@ -667,7 +667,6 @@ def _test_deprecated_module_inner(outdated_method, deprecation_messages):
             deadline='v0.20',
             count=len(deprecation_messages),
         ):
-            import warnings

             warnings.simplefilter('always')
             outdated_method()
@@ -785,6 +784,7 @@ def _test_broken_module_1_inner():


 def _test_broken_module_2_inner():
+    warnings.simplefilter('always')
     with cirq.testing.assert_deprecated(deadline="v0.20", count=None):
         with pytest.raises(
             DeprecatedModuleImportError,
@@ -800,6 +800,7 @@ def _test_broken_module_2_inner():
 def _test_broken_module_3_inner():
     import cirq.testing._compat_test_data

+    warnings.simplefilter('always')
     with cirq.testing.assert_deprecated(deadline="v0.20", count=None):
         with pytest.raises(
             DeprecatedModuleImportError,
```

**Comment by dabacon** [comment]
@pavoljuhas thanks for figuring that out.  Windows always does spawn, which I guess resets the warning, so I think your fix fixes things.

**Review by MichaelBroughton — APPROVED** [review]

**Pull request merged**
