### PR TITLE
#1263 Pass parameter_sweeps in jobs api rather than program api of Quantum …

### PR DESCRIPTION
**Pull request by iamvamsi**
…Engine

### CODE REVIEW

**Comment by iamvamsi** [comment]
Please review and let me know if I am missing something here.

**Comment by iamvamsi** [comment]
#1263

**Comment by dabacon** [comment]
Have you been able to test this out against the Engine API?

**Comment by iamvamsi** [comment]
Dave, I didn't test it. Can you please point to any doc about procedure to do the same.

**Comment by dabacon** [comment]
Sent you an email with instructions.

**Comment by vtomole** [comment]
@iamvamsikrishnad What's the update on this?

**Comment by Strilanc** [comment]
Closed as stale.

**Pull request closed without merging**
