### PR TITLE
Remove EngineTimeSlot

### PR DESCRIPTION
**Pull request by dstrain115**
- It looks like this wrapper got created but never used.
- It does not provide much value over the proto values directly,
so I am just going to delete it.
- This also fixes the typing which incorrectly says that the
schedule is returned as a EngineTimeSlot, but it is actually a
QuantumTimeSlot.

While technically a breaking change, it would be quite surprising
if anyone is dependent on this wrapper class, as it has never been used
anywhere.

BREAKING CHANGE=Removed EngineTimeSlot without deprecation, (minimal to no usage).

### CODE REVIEW

**Review by MichaelBroughton — APPROVED** [review]
This seems fine to me (in my travels with engine I never used this). If we want to go ahead and cut this without deprecating, would you mind adding the breaking_change label and a description of the break at the bottom of your PR description ?

cc: @mpharrigan

**Review by wcourtney — APPROVED** [review]
LGTM

**Comment by mpharrigan** [comment]
hello from cc land. Looks fine, although I agree this should be labeled with breaking change

**Comment by mpharrigan** [comment]
this actually broke a utility in recirq :facepalm:

**Comment by mpharrigan** [comment]
https://github.com/quantumlib/ReCirq/pull/140

**Pull request merged**
