### PR TITLE
CliffordGate**0.5/-0.5

### PR DESCRIPTION
**Pull request by vtomole**
This one https://github.com/quantumlib/Cirq/pull/1417 automatically closed after not "pull rebasing".

### CODE REVIEW

**Comment by vtomole** [comment]
@Strilanc Ready for the second round The formatting can be annoying. I always use [autopep8](https://github.com/hhatto/autopep8) before committing and "non relevant" code always seem to change. I'm wondering if we should define a standard formatter to avoid this.

**Comment by Strilanc** [comment]
@vtomole Yes, we should definitely have a formatting check as part of the continuous integration.

**Comment by Strilanc** [comment]
At some point I'll write an incremental format checker + incremental format applier, that only checks and only touches code you've edited.

**Comment by vtomole** [comment]
@Strilanc  Fix the nits by using Emacs to format and it looks like it has different opinions from autopep8.

**Comment by vtomole** [comment]
Ready for merge.

**Pull request merged**
