### PR TITLE
Base class for quantum states

### LINKED ISSUE #4827: Separate out the quantum part of ActOnArgs into own class
**Describe your design idea/issue**

Right now, the ActOnArgs hierarchy design is such that ActOnArgs (the base class) contains all the shared stuff like measurement logs, qid shape, etc., and the subclasses contain their quantum representations. This works, but I've always felt it was a little clunky.

A result of this approach is that `ActOnArgs.kron()`, etc., do the kronning of the qid shape, and then calls `self._on_kron()`, which delegates the subclasses to kron the quantum states. Again, this works but feels clunky.

It may be worth exploring a change where the quantum part is placed into its own class. So we'd have a StateVectorQuantumState, a DensityMatrixQuantumState, etc, that implement a SimulatorQuantumState interface specifying `copy`, `kron`, etc. Then instead of requiring ActOnArgs subclasses to implement `_on_kron`, the new kron routine is just `target.quantum_state = self.quantum_state.kron(other.quantum_state)`.

Ultimately from there we may be able to kill off the subclasses and just make ActOnArgs generic like `ActOnArgs[TSimulatorQuantumState]`.

### PR DESCRIPTION
**Pull request by daxfohl**
Creates a base class for all the quantum state classes created in #4979, and uses the inheritance to push the implementation of `ActOn<State>Args.kron`, `factor`, etc into the base class.

Closes #4827
Resolves https://github.com/quantumlib/Cirq/pull/3841#discussion_r580705505 that's been bugging me for a year.

### CODE REVIEW

**Comment by daxfohl** [comment]
@95-martin-orion This is ready, building on the previous one. No rush, can go in after v0.15

**Review by 95-martin-orion — APPROVED** [review]
Net lines removed? Sounds like a win to me :)

**Comment by daxfohl** [comment]
@MichaelBroughton might #5144 have broken this lint check?

**Comment by daxfohl** [comment]
@95-martin-orion @MichaelBroughton This failed due to some pylint flake. I rebased and it seems to be working again, ready to push.

**Pull request merged**
