### PR TITLE
Basic arithmetic example

### PR DESCRIPTION
**Pull request by enakai00**
Hi, I created one more example for basic arithmetics (addition and multiplication).

### CODE REVIEW

**Comment by Strilanc** [comment]
@dabacon What do you think of this example?

I'm worried that arithmetic is not something you can do with NISQ machines, and we already have too many non-NISQ examples in the example folder. Maybe we should put them all under a "not-nisq" subfolder?

**Comment by Strilanc** [comment]
@dabacon still waiting for your thoughts

**Comment by Strilanc** [comment]
@dabacon edit this and merge it

**Comment by dabacon** [comment]
CLA was signed by original owner and I updated, also under CLA.

**Pull request merged**
