### PR TITLE
Update api.rst and cleanup and standardize init files.

### PR DESCRIPTION
**Pull request by dabacon**
Made a pass over all classes in main cirq.__init__ to populate api.rst.  

Inits now alphabetized and follow format conventions.

### CODE REVIEW

**Comment by dabacon** [comment]
Fixes #1535

**Comment by vtomole** [comment]
Remove `contrib.jobs` from `api.rst` as it doesn't exists anymore.

**Comment by Strilanc** [comment]
What warnings specifically? Is your `origin/master` up to date?

**Comment by vtomole** [comment]
```
WARNING: [autosummary] failed to import 'cirq.contrib.jobs': no module named cirq.contrib.jobs
```
On the latest code off of master with this merged

**Pull request merged**
