### PR TITLE
Avoid triggering KeyError to check key presence in dicts

### PR DESCRIPTION
**Pull request by viathor**

### CODE REVIEW

**Review by HGSilveri — APPROVED** [review]
No issues on my side.

**Review by pschindler — APPROVED** [review]
No issues from my side

**Review by 95-martin-orion — APPROVED** [review]

**Comment by mpharrigan** [comment]
what motivated this change? As I understand it, idiomatic python likes try/excepts under the "EAFP" https://docs.python.org/3/glossary.html approach. Here's another thing I found: https://devblogs.microsoft.com/python/idiomatic-python-eafp-versus-lbyl

Note that I personally disagree with Python on this, so I'm fine with this change :) was just wondering if other corner cases motivated it or if it's just a style thing

**Comment by 95-martin-orion** [comment]
> what motivated this change?

I had an impression that this was idiomatic Python when writing #3546, but couldn't find the docs to back it up - AFAICT @viathor wrote this in response to the discussion there. (Coming from a C++ background, I'm also wary of the Python idiom here.)

**Comment by viathor** [comment]
Yeah, I was being wrong [here](https://github.com/quantumlib/Cirq/pull/3546#discussion_r534532837). Sorry about that, @95-martin-orion. See my response there.

**Pull request merged**
