### PR TITLE
Add `attrs` lower bound in requirements.txt

### PR DESCRIPTION
**Pull request by ryanhill1**
```bash
$ pip install cirq-core
$ pip install 'attrs==21.2.0'
$ python
>>> import cirq
...
File ~/anaconda3/envs/py312/lib/python3.12/site-packages/cirq/transformers/gauge_compiling/gauge_compiling.py:23
     20 import functools
     22 from dataclasses import dataclass
---> 23 from attrs import frozen, field
     24 import numpy as np
     26 from cirq.transformers import transformer_api

ModuleNotFoundError: No module named 'attrs'

$ pip install 'attrs==21.3.0'
$ python
>>> import cirq
>>> # works
```

Any `attrs<21.3.0` fails for me when I try to `import cirq`. And any `attrs>=21.3.0` seems to work.

Reference: 
- https://pypi.org/project/attrs/#history
- https://stackoverflow.com/a/75610797/14781553

### CODE REVIEW

**Review by pavoljuhas — COMMENTED** [review]
Unfortunately, this breaks the pip dependency resolver and the [ci tests]( https://github.com/quantumlib/Cirq/actions/runs/9359292431/job/25762759541?pr=6633) even whilst `uv pip compile dev_tools/requirements/dev.env.txt` can find a viable set of packages.

Installation of cirq-core to a fresh virtual environment brings in the latest attrs-23.2.0.
Installation of the whole cirq suite brings attrs-21.4.0 - both of these cases satisfy the required minimum version.

I suggest to hold this for later until after the merge of #6281 which will loosen the maximum attrs version from a transitive dependency.

**Comment by NoureldinYosri** [comment]
I don't see how `ModuleNotFoundError: No module named 'attrs'` could be caused by an old `attrs` version?! ... if the error was that it can't find one of the functions/classes of the library then it would have made sense ... but module not found is a different thing

**Comment by maffoo** [comment]
@NoureldinYosri, see the `attrs` [changelog](https://www.attrs.org/en/stable/changelog.html#id13). While the package on pypi has always been called `attrs` so that is what you would install (`pip install attrs`), the python package that you would import was previously called `attr` (`import attr`). This was confusing, so they added an `attrs` python package which matches the install name, and this first landed in 21.3.0.

**Comment by simulified** [comment]
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Review by pavoljuhas — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
