### PR TITLE
Document noise representations

### PR DESCRIPTION
**Pull request by 95-martin-orion**
Doc for capturing different representations of noise in Cirq.

### CODE REVIEW

**Comment by 95-martin-orion** [comment]
CC @augustehirth

This is my initial pass at the doc we discussed - how close is it to what you had in mind? Are there any topics missing? Should we include code examples?

**Comment by 95-martin-orion** [comment]
Tests are blocked on #5480.

**Comment by 95-martin-orion** [comment]
Quantum walks doc got caught by the auto-formatter, it can be ignored.

**Review by augustehirth — APPROVED** [review]
LGTM

**Review by MichaelBroughton — APPROVED** [review]

**Pull request merged**
