### PR TITLE
Fix `PauliString.pass_operations_over` not supporting common gates

### PR DESCRIPTION
**Pull request by Strilanc**
- Add `_decompose_into_clifford_` method to `GateOperation`
- Add `_decompose_into_clifford_with_qubits_` method to several common gates
- Add `PauliString.conjugated_by`, which accepts an `OP_TREE` defining a composite Clifford operation in Circuit order. This differs from `pass_ops_over`, because `pass_ops_over` takes a list of operations in reverse circuit order (which is confusing).
- Fix op_gate_isinstance type annotation not allowing type tuples
- Add `PauliString.dense` method

Code such as the following now works:

```
a, b = cirq.LineQubit.range(2)
print(cirq.X(a).pass_operations_over([cirq.H(a)]))
print(cirq.X(a).conjugated_by(cirq.Circuit(cirq.H(a), cirq.CNOT(a, b))))
```

```
Z(0)
Z(0)*X(1)
```

Fixes https://github.com/quantumlib/Cirq/issues/2179

### CODE REVIEW

**Comment by Strilanc** [comment]
Reviewers: please check that `conjugated_by` does the thing that you would expect based on the name. Ideally, predict it before reading the code or the tests.

**Comment by Strilanc** [comment]
Yes, I kept the decompose methods private without a publicly exposed method because I didn't want to commit to the interface yet.

**Comment by mpharrigan** [comment]
is anything blocking this?

**Comment by Strilanc** [comment]
@mpharrigan Nothing except actually getting a review of it.

**Pull request merged**
