### PR TITLE
More graph device

### PR DESCRIPTION
**Pull request by bryano**

### CODE REVIEW

**Comment by bryano** [comment]
I can't reproduce the failing test on my machine. It looks like `sorted` isn't doing the right thing, which is weird.

**Comment by Strilanc** [comment]
At the sync meeting we decided to put this in contrib.

**Comment by vtomole** [comment]
@bryano  Please `QubitId` -> `Qid`.

**Comment by Strilanc** [comment]
Still blocked on the Qid change, and getting very stale. I'll close in two weeks if there are no updates.

**Comment by bryano** [comment]
@Strilanc PTAL

**Pull request merged**
