### PR TITLE
GateFamily: do not serialize gates_to_accept and gates_to_ignore when empty

### PR DESCRIPTION
**Pull request by verult**
GateFamily has existed prior to the last release, while GateFamily tag support has not gone into a release yet. Removing empty lists in serialized JSON before the next release as recommended to ensure backward compatibility.

@95-martin-orion

### CODE REVIEW

**Comment by 95-martin-orion** [comment]
What motivates this change? It's generally only necessary to omit empty field when trying to maintain backwards compatibility with old versions of a class - is that what's happening here?

**Comment by verult** [comment]
That's right, similar to the situation in GridDevice. Updated the PR description to be more specific.

**Review by 95-martin-orion — APPROVED** [review]
Cool, this all checks out.

**Comment by verult** [comment]
CI failures look similar to precision issues here: https://github.com/quantumlib/Cirq/runs/6926154638?check_suite_focus=true

cc @dabacon @MichaelBroughton

**Pull request merged**
