### PR TITLE
Rename `cirq_ft.Registers` to `cirq_ft.Signature` to match data types in Qualtran

### PR DESCRIPTION
**Pull request by tanujkhattar**
This PR further brings the quantumd data types infrastructure in Cirq-FT closer to Qualtran. Specifically, it does the following two changes:

1. Add a `Side` attribute to the `Register` class. A `LEFT` register denotes qubit deallocation and a `RIGHT` register denotes qubit allocation, similar to Qualtran. In Cirq, both these registers still continue to use globally allocated qubits but the semantics are preserved when writing gates.
2. Rename the `cirq_ft.Registers` class to `cirq_ft.Signature` and make the interfaces identical to those in Qualtran. 

This is the final piece in a series of changes to make enable Cirq-FT and Qualtran Bloqs share the same fundamental quantum data types (i.e. `Register` and `Signature` classes). 

cc @mpharrigan @fdmalone

### CODE REVIEW

**Review by fdmalone — APPROVED** [review]
Should there be a tests checking that allocating and deallocated qubits have the correct "side"?

**Comment by tanujkhattar** [comment]
The idea of adding `Side` to the signature in Cirq is to make it part of the signature that the gate expects you to provide clean ancillas (if side = RIGHT) OR that the gate will leave the qubit in a clean state (if side=LEFT). Right now, this is expressed only as comments on the gate class (eg: the `And` gate). 

This is an improvement over the current state of the art (explicit signature instead of a comment) but it still relies on the user doing the right thing and following the signature. Adding automated tests to make sure the qubit provided to a gate with RIGHT registers are actually clean (or vice versa for LEFT registers) can be done as a future improvement but is out of scope for the current PR.

**Comment by mpharrigan** [comment]
next time please consider doing the automated rename and manual edits in two separate commits :)

**Comment by tanujkhattar** [comment]
Pycharm automated refactor didn't work very well for me so I had to do manual edits anyway, but point taken that I could've done the adding of `side` attribute in a follow up PR

**Comment by mpharrigan** [comment]
ah no worries. if it was all manual then you can do whatever you want because that's a lot of changes to do manually !

**Pull request merged**
