### PR TITLE
[WIP] PhasedISwapPowGate constructor does not take global_shift

### LINKED ISSUE #4570: PhasedISwapPowGate constructor does not take global_shift
**Description of the issue**
`PhasedISwapPowGate` is an `EigenGate` but unlike most other eigen gates, it's constructor does not take `global_shift` as an argument and it always defaults to 0. 

For consistency, we should add an additional `global_shift` parameter to `PhasedISwapPowGate`.

**Cirq version**
0.13.0.dev

### PR DESCRIPTION
**Pull request by anonymousr007**
Fixes #4570

### CODE REVIEW

**Review by tanujkhattar — CHANGES_REQUESTED** [review]
Please add tests / test cases to existing tests which probe the behavior of the class with different values passed for the `global_shift` parameter.

**Comment by anonymousr007** [comment]
> Please add tests / test cases to existing tests which probe the behavior of the class with different values passed for the `global_shift` parameter.

Can you please share some resource ? It is new for me 😄

**Comment by tanujkhattar** [comment]
@anonymousr007 You can take a look at pytest docs to get a high level overview of how tests work (see https://docs.pytest.org/en/6.2.x/). You should also look at cirq-core/cirq/ops/phased_iswap_gate_test.py file which stores existing tests for the class that you are modifying. 

As part of this PR, you'd have to add additional tests in cirq-core/cirq/ops/phased_iswap_gate_test.py such that newly added behavior is tested. You can run the existing and newly added tests locally before updating the PR by following the guidelines mentioned in https://github.com/quantumlib/Cirq/blob/master/docs/dev/development.md#continuous-integration-and-local-testing

**Comment by tanujkhattar** [comment]
@anonymousr007 Gentle reminder. Please address the comments so that we can approve the PR.

**Comment by vtomole** [comment]
Closing as stale and opening https://github.com/quantumlib/Cirq/pull/5328

**Pull request closed without merging**
