### PR TITLE
Pass shell script arguments without splitting

### PR DESCRIPTION
**Pull request by pavoljuhas**
Unquoted $@ splits shell script arguments on whitespace.
Use the "$@" form to pass arguments exactly as received.

### CODE REVIEW

**Review by MichaelBroughton — APPROVED** [review]
LGTM! Kinda surprising how many of these there.

**Comment by 95-martin-orion** [comment]
This change appears to break coverage checks. In a branch which introduces new test files, I get `ERROR: file or directory not found` for each of the new test files. Reverting the `check/pytest` change in this PR fixes this issue.

We should revisit this and only quote the `$@` instances that actually need quotes.

**Comment by vtomole** [comment]
If I recall,  shellcheck: https://github.com/koalaman/shellcheck flags any `$@` that don't have quotes.

**Comment by pavoljuhas** [comment]
`"$@"` passes shell arguments exactly as they were provided, ie, `foo bar` as `foo bar` instead of `foo` and `bar`.
If this causes a failure it seems that script caller runs check/pytest with a single "foo bar" argument and expects it to be split it.

@95-martin-orion - can you please provide more detail how to run the coverage check that fails?

**Comment by 95-martin-orion** [comment]
It seems like this is an artifact of my local client - the same code is passing CI checks on Github. I'll review my setup and update here if/when I figure out what's wrong.

**Comment by mpharrigan** [comment]
I'm seeing this problem as well. We need to fix it

**Comment by mpharrigan** [comment]
```diff
diff --git a/check/pytest-changed-files-and-incremental-coverage b/check/pytest-changed-files-and-incremental-coverage
index 42108016..b21fc4f7 100755
--- a/check/pytest-changed-files-and-incremental-coverage
+++ b/check/pytest-changed-files-and-incremental-coverage
@@ -86,8 +86,8 @@ fi
 source dev_tools/pypath
 
 # Run tests while producing coverage files.
-check/pytest "${changed_python_tests[@]}" \
-    "${cov_changed_python_file_dirs[@]}" \
+check/pytest ${changed_python_tests[@]} \
+    ${cov_changed_python_file_dirs[@]} \
     --cov-report=annotate \
     --cov-config=dev_tools/conf/.coveragerc
 pytest_result=$?
```

fixes it for me

**Comment by pavoljuhas** [comment]
The issue is that the `cov_changed_python_file_dirs` and `changed_python_tests` parameters are defined as scalar strings (lines [61]( https://github.com/quantumlib/Cirq/blob/42ac9dafcdb110dbeaf09b66d8d5203e8edc39eb/check/pytest-changed-files-and-incremental-coverage#L61) and 69), but then expanded as arrays - effectively as a one multi-line string, when passed to check/pytest.  Let me adjust it so it is always using arrays.

**Comment by pavoljuhas** [comment]
@mpharriga - please see #4703 for the fix.

**Pull request merged**
