### PR TITLE
Implement cirq.eigencomponents() for FSimGate

### LINKED ISSUE #2492: Implement cirq.eigencomponents()
Conclusion of discussion in #2481 .

### PR DESCRIPTION
**Pull request by tonybruguier-google**
Fixes #2492

### CODE REVIEW

**Comment by balopat** [comment]
@tonybruguier-google thanks for all the work :D 
A nit before I review this: the "Fixes #2492." should go in the comment of the PR, and the title should be more descriptive. Github recognizes the link between the PR only if this text is in the PR comment. 
The title will become the commit message automatically when Cirqbot merges the PR after approval.

**Comment by tonybruguier-google** [comment]
Fixes #2492

**Comment by balopat** [comment]
> Fixes #2492

I meant the main section / it's called a comment here, sorry for the confusing language! 

image

**Comment by tonybruguier-google** [comment]
Modified the comment. Sorry about this.

**Comment by balopat** [comment]
> Modified the comment. Sorry about this.

No worries, at all, no apologies necessary! :) PRs can have both a description and if there is an issue it is for, the reference, see https://github.com/quantumlib/Cirq/pull/3163 as an example.

**Comment by tonybruguier-google** [comment]
Sounds good. Will withdraw. Thanks for taking the time to review the code.

**Pull request closed without merging**
