### PR TITLE
Fix for issue #2777: it makes no sense to call simulator.run when ignore_measurement_results has been set to True

### LINKED ISSUE #2777: Density matrix simulator sometimes returns measurement results when ignore_measurement_results is True
Split off from #2567 .
Input:
```
import cirq

q = cirq.LineQubit(0)
circuit1 = cirq.Circuit(cirq.measure(q))
circuit2 = circuit1 + cirq.I(q)

print('Circuit 1:')
print(circuit1)
print()
print('Circuit2:')
print(circuit2)
print()

simulator = cirq.DensityMatrixSimulator(noise=cirq.X, ignore_measurement_results=True)
result1 = simulator.run(circuit1, repetitions=10)
result2 = simulator.run(circuit2, repetitions=10)

print('Result 1:')
print(result1)
print()
print('Result 2:')
print(result2)
print()
```
Output:
```
Circuit 1:
0: ───M───

Circuit2:
0: ───M───I───

Result 1:
0=1111111111

Result 2:

```

### PR DESCRIPTION
**Pull request by akushnarov**
Raises a ValueError for DensityMatrixSimulator.run when ignore_measurement_results=True.

Fixes #2777.

### CODE REVIEW

**Review by vtomole — CHANGES_REQUESTED** [review]
What doesn't make sense about it? When `ignore_measurement_results=true` the measurement is treated as a dephase instead of a collapse of the wavefunction.

**Review by vtomole — COMMENTED** [review]
Oh i'm just seeing this: https://github.com/quantumlib/Cirq/issues/2777#issuecomment-587959511

**Review by vtomole — APPROVED** [review]

**Comment by dstrain115** [comment]
Please add a test for this.

Also, you can fix formatting by running `check/format-incremental --apply`

**Comment by akushnarov** [comment]
@balopat could you please check this one?

**Review by balopat — APPROVED** [review]

**Pull request merged**
