### PR TITLE
Remove dependency on the flynt tool

### LINKED ISSUE #6171: Replace flynt checker with pylint consider-using-f-string
**Description of the issue**

flynt is a tool for converting `%-format` and `"{}".format()` strings to Python f-strings.
It is used in the [check/format-incremental](https://github.com/quantumlib/Cirq/blob/421d492b293486f844619b7de936994652808985/check/format-incremental) script and also as an example for package metadata reading in a unit tests [here](https://github.com/quantumlib/Cirq/blob/421d492b293486f844619b7de936994652808985/cirq-core/cirq/_compat_test.py#L739).

The same functionality can be provided by the [consider-using-f-string](https://pylint.pycqa.org/en/latest/user_guide/messages/convention/consider-using-f-string.html) pylint rule.

I propose to use pylint rule instead of pylint and also replace flynt usage in the unit test with a more common package.

**Cirq version**

1.2.0.dev at 3f8d83ac247ef07f70668db7bae5f27f46713cbe

### PR DESCRIPTION
**Pull request by pavoljuhas**
- pylint - enable consider-using-f-string check
- flynt - check and fix all python sources
- Test package metadata with numpy rather than flynt

Partially fixes #6171

### CODE REVIEW

**Comment by tanujkhattar** [comment]
Is flynt not able to convert files for which have added explicit TODOs? It looks like we are adding a LOT of TODOs to the codebase -- what's the plan to get rid of them? Can we experiment with automated tools and change these files as part of this PR itself instead of adding a that many TODOs ?

**Comment by pavoljuhas** [comment]
> Is flynt not able to convert files for which have added explicit TODOs? It looks like we are adding a LOT of TODOs to the codebase -- what's the plan to get rid of them? Can we experiment with automated tools and change these files as part of this PR itself instead of adding a that many TODOs ?

The plan is to address TODO-s in a follow-up PR which will only change the string expressions without changing their values, https://github.com/quantumlib/Cirq/issues/6171#issuecomment-1610366330.  The second PR can be added to [.git-blame-ignore-revs](https://github.com/quantumlib/Cirq/blob/master/.git-blame-ignore-revs) without masking away the actual changes in `.pylintrc` and `_compat_test.py`.

As for the automated changes, I tested with flynt on one file and it seems to do the job.  Still I would like to put these no-op changes to a separate PR.

**Review by tanujkhattar — APPROVED** [review]
@pavoljuhas Okay, I'll approve this PR and let's merge it; but can you make sure we get in the follow up soon so we don't leave the TODOs for a long time?

**Comment by pavoljuhas** [comment]
> @pavoljuhas Okay, I'll approve this PR and let's merge it; but can you make sure we get in the follow up soon so we don't leave the TODOs for a long time?

Sounds good will do.

**Pull request merged**
