### PR TITLE
Fix backwards incompatible pandas usage.

### PR DESCRIPTION
**Pull request by MichaelBroughton**
Experiment with latest CI break.

### CODE REVIEW

**Comment by vtomole** [comment]
We have a pandas break on this run: https://github.com/quantumlib/Cirq/runs/4914290551?check_suite_focus=true

**Comment by vtomole** [comment]
https://github.com/quantumlib/Cirq/runs/4914785919?check_suite_focus=true as well:

```
pandas.errors.InvalidIndexError: (slice(None, None, None), None)
```

**Comment by MichaelBroughton** [comment]
This PR will fix those.

**Review by vtomole — APPROVED** [review]
LGTM

**Pull request merged**
