### PR TITLE
[WIP] Improve circuit export to Quirk URLs

### PR DESCRIPTION
**Pull request by Strilanc**
This is working towards making it possible to take a Quirk URL and produce a simulable `cirq.Circuit` instance. This involves defining quite a lot of gates; I've tried to do it in a minimalist fashion.

To give a sense, each arithmetic gate is taking up about one line (with a decent amount of machinery hiding to make this possible):

```python
    yield from reg_arithmetic_family("^=A", lambda x, a: x ^ a)
    yield from reg_arithmetic_family("+cntA", lambda x, a: x + popcnt(a))
    yield from reg_arithmetic_family("-cntA", lambda x, a: x - popcnt(a))
    yield from reg_arithmetic_family(
        "Flip<A", lambda x, a: a - x - 1 if x < a else x)
    yield from reg_arithmetic_family(
        "*AmodR", lambda x, a, r: (x * a) % r
        if x < r and modular_multiplicative_inverse(a, r) else x)
```

These gates will not be exposed at the top level. They only exist to make parsing possible.

### CODE REVIEW

**Comment by vtomole** [comment]
Context please? I've seen some changes from here in other PRS.

**Comment by Strilanc** [comment]
Those PRs were pulled off of this one. I've edited the main message.

**Comment by dabacon** [comment]
Is there more that needs to be mined from this?  [WIP] for long periods of time should probably be kept in your own github repos :)

**Comment by Strilanc** [comment]
Yes, there's more still being pulled off of it.

**Comment by Strilanc** [comment]
All relevant PRs have been extracted.

**Pull request closed without merging**
