### PR TITLE
Move over to uploading cirq-dev to quantumlibdev pypi on prod

### PR DESCRIPTION
**Pull request by dabacon**
Pushing to quantumlibdev so that there is no possibility of corrupting quantum lib repos.

### CODE REVIEW

**Comment by cduck** [comment]
@dabacon You didn't verify quantumlibdev's email address.
```
HTTPError: 400 Client Error: User 'quantumlibdev' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.for more information. for url: https://upload.pypi.org/legacy/
```

**Comment by dabacon** [comment]
Yeah email is now verified.

**Comment by dabacon** [comment]
It worked :)

**Comment by cduck** [comment]
I ran verify-published-package.sh (with `PROJECT_NAME=cirq-dev`) and got this error during testing:
```
$ ./verify-published-package.sh 0.6.0.dev20190816172027

python3
Working in a fresh virtualenv at /tmp/verify-published-package.IehUzGHVeDYmop77/python3
Already using interpreter /usr/bin/python3
Installing cirq-dev==0.6.0.dev20190816172027 from PROD pypi
Checking that code executes
(0, 0)───(0, 1)───(0, 2)───(0, 3)───(0, 4)───(0, 5)───(0, 6)───(0, 7)───(0, 8)───(0, 9)───(0, 10)
│        │        │        │        │        │        │        │        │        │        │
│        │        │        │        │        │        │        │        │        │        │
(1, 0)───(1, 1)───(1, 2)───(1, 3)───(1, 4)───(1, 5)───(1, 6)───(1, 7)───(1, 8)───(1, 9)───(1, 10)
0: ───@───
      │
1: ───@───
Installing pytest requirements
Running cirq tests

no tests ran in 0.00s
ERROR: file not found: /tmp/verify-published-package.IehUzGHVeDYmop77/python3/lib/python3.6/site-packages/cirq-dev

FAILED
```

**Comment by dabacon** [comment]
There are now two things dev pushes of cirq and dev pushes of cirq-dev.  We probably need to deprecate the former.

**Pull request merged**
