### PR TITLE
Move scipy from runtime requirements to dev requirements

### PR DESCRIPTION
**Pull request by Strilanc**
- It's only used in an example

### CODE REVIEW

**Comment by Strilanc** [comment]
Note: one of the downsides of doing this is that the tests won't pass unless you have the dev requirements. Maybe not such a good idea?

**Comment by cduck** [comment]
But pytest is a dev requirement.

**Comment by dabacon** [comment]
One reason to keep scipy around would be for optimization algorithms.

**Comment by Strilanc** [comment]
Yes, it may become a dependency anyways soon enough.

Perhaps we should simply weaken the version requirement.

**Comment by Strilanc** [comment]
Obsoleted by https://github.com/quantumlib/Cirq/pull/804 removing the version specifier on scipy

**Pull request closed without merging**
