### PR TITLE
Fix pandas dependency

### PR DESCRIPTION
**Pull request by 95-martin-orion**
Error highlighted by @akushnarov: `pandas requires NumPy >= 1.6.1 due to datetime64 dependency`.

### CODE REVIEW

**Comment by 95-martin-orion** [comment]
`numpy.random.default_rng` was added in v1.17, so that's our actual minimum version. The reason that `numpy~=1.16` still passed our test suite is that `~=` gets the latest compatible version (i.e. v1.*); however, it only guarantees that this version will be at least v1.16.

**Comment by 95-martin-orion** [comment]
Okay, this is getting strange: `numpy~=1.17` still gives the `pandas requires NumPy >= 1.6.1` error.

I found [this SO question](https://stackoverflow.com/questions/12436979/how-to-fix-python-numpy-pandas-installation) which suggests that MacOS has a default numpy version that may be causing this. Recommended fix is `pip install numpy --upgrade` or manually deleting the default `numpy` install.

I can only assume that this didn't appear until now because of some change to `pandas` which increased its minimum numpy requirement.

**Comment by 95-martin-orion** [comment]
Based on the explosion of package-version downloads in the logs and an apparent change from pip-20.2.4 to 20.3, I suspect this is actually caused by https://github.com/pypa/pip/issues/9215. Closing in lieu of a more appropriate fix.

**Comment by 95-martin-orion** [comment]
> Closing in lieu of a more appropriate fix.

See #3574.

**Comment by mpharrigan** [comment]
Can we delete this branch?

**Pull request closed without merging**
