### PR TITLE
Fix Windows failing ion tests

### LINKED ISSUE #1662: `Y^-0.5` not being converted to `PhasedX(-0.5)^0.5` on Ion related tests in Windows.
As a reference: https://travis-ci.com/quantumlib/Cirq/jobs/201514754

For ` test_convert_to_ion_circuit`

```
E       AssertionError: Circuit's text diagram differs from the desired diagram.
E
E       Diagram of actual circuit:
E       (0, 0): ───X───────MS(0.25π)───X^-0.5──────────MS(0.25π)───
E                          │                           │
E       (0, 1): ───Y^0.5───MS(0.25π)───Y^-0.5───S^-1───MS(0.25π)───
E
E       Desired text diagram:
E       (0, 0): ───X───────MS(0.25π)───X^-0.5─────────────────────MS(0.25π)───
E                          │                                      │
E       (0, 1): ───Y^0.5───MS(0.25π)───PhasedX(-0.5)^0.5───S^-1───MS(0.25π)───
E
E       Highlighted differences:
E       (0, 0): ───X───────MS(0.25π)───X^-0.5──────────█████████──████████████
E                          │                           ████████████
E       (0, 1): ───Y^0.5───MS(0.25π)───█████████████████████████──████████████

```

For `test_decomposition`
```
E       AssertionError: Circuit's text diagram differs from the desired diagram.
E
E       Diagram of actual circuit:
E       0: ───Y^0.5───Z───MS(0.25π)───Y^-0.5───S^-1───
E                         │
E       1: ───────────────MS(0.25π)───X^-0.5──────────
E
E       Desired text diagram:
E       0: ───Y^0.5───Z───MS(0.25π)───PhasedX(-0.5)^0.5───S^-1───
E                         │
E       1: ───────────────MS(0.25π)───X^-0.5─────────────────────
E
E       Highlighted differences:
E       0: ───Y^0.5───Z───MS(0.25π)───███████████████████████████
E                         │
E       1: ───────────────MS(0.25π)───X^-0.5──────────███████████
```
CC: @mlihc15 , @c-poole

### PR DESCRIPTION
**Pull request by c-poole**
Removes circuit diagram comparisons and instead checks if the decomposed circuits pass `validate_circuits` and `cirq.testing.assert_circuits_with_terminal_measurements_are_equivalent` when compared with the non-decomposed circuit. Fixes #1662 .

### CODE REVIEW

**Comment by c-poole** [comment]
If someone would kindly explain to this github noob how to avoid having commits from previously merged PRs in each of my new PRs that would be greatly appreciated.

**Comment by vtomole** [comment]
@c-poole It's not a big deal, but it's because you are doing all your work in one branch (`c-poole:master`). The Github flow is to create a new branch off of master for every pull request and delete that branch after the feature has been merged in.

**Comment by c-poole** [comment]
@vtomole  so if I wanted to switch to that process, would it be necessary to delete and re-fork since any branch I make off of my forked master will still have these commits in the history?

**Comment by vtomole** [comment]
@c-poole Not at all. Just branch of your master for each pull request and everything should be fine.

**Comment by vtomole** [comment]
Just confirmed that these tests are passing on our Travis: https://travis-ci.com/quantumlib/Cirq/jobs/202334211

**Comment by mlihc15** [comment]
Thanks for the fix Cody! Yeah I was thinking about changing these tests. I created them following the tests they had for the google device, but this solution makes a lot more sense.

**Comment by c-poole** [comment]
Excellent, thanks for the approval. We still need an approving review from someone with write-access to merge.

**Pull request merged**
