### PR TITLE
Exclude IdentityGate from CircuitSerializer serialization.

### LINKED ISSUE #4833: Cannot serialize identity gate on Quantum Engine
**Description of the issue**

Cannot serialize identity gate when using SQRT_ISWAP_GATESET.

**How to reproduce the issue**

```python
sampler = engine.get_sampler(processor_id='...', gate_set=cg.SQRT_ISWAP_GATESET)
q = cirq.GridQubit(7, 4)
c = cirq.Circuit(cirq.I(q))
r = sampler.run(c, repetitions=1)
...
ValueError: Cannot serialize op cirq.I(cirq.GridQubit(7, 4)) of type <class 'cirq.ops.identity.IdentityGate'>
```

**Cirq version**

```
0.14.0.dev20211210220312
```

### PR DESCRIPTION
**Pull request by verult**
Operation and Moment message construction logic is changed to not add an empty message in the corner case where a circuit only consists of identity gates.

Fixes #4833

### CODE REVIEW

**Review by maffoo — COMMENTED** [review]
I would suggest that serialization should try to preserve the input circuit as exactly as possible, rather than making changes like this. Changes or optimizations to circuits are the job of transformers, which can be invoked separately, but just serializing/deserializing should be as information-preserving as possible.

Regarding the specific case of identity gates, note that in some cases they can have meaning, for example, internally we use identities with special tags to mark places where we want to insert dynamicaly decoupling gates in circuits. We would want such gates to be preserved in the circuits to be preserved, along with their tags, when serializing.

**Comment by verult** [comment]
cc @dstrain115 @viathor

**Comment by vtomole** [comment]
We'll bring this up at today's Cirq sync.

**Comment by verult** [comment]
Discussed with @dstrain115 offline and he's onboard with @maffoo 's suggestion. Closing this PR and will update the issue with next steps.

**Pull request closed without merging**
