### PR TITLE
Update start notebook to use `get_engine` instead of `get_qcs_objects_for_notebook`

### PR DESCRIPTION
**Pull request by senecameeks**
Addresses #6427 by removing the incorrect `processor_id` in the notebook. 

Although this doesn't fix the underlying issue as to why `get_qcs_objects_for_notebook` is incorrect and doesn't address Will's second point in his [comment](https://github.com/quantumlib/Cirq/issues/6427#issuecomment-1915313677) 

FYI, I verified this works as a good replacement for `get_qcs_objects_for_notebook`

### CODE REVIEW

**Review by eliottrosenberg — APPROVED** [review]
LGTM, thanks!

**Comment by NoureldinYosri** [comment]
this might not work if it's run from outside corp network in which case authentication is needed  which is part of `get_qcs_objects_for_notebook` https://github.com/quantumlib/Cirq/blob/eef7c5c9309fcdb9254a295491facee3118c2279/cirq-google/cirq_google/engine/qcs_notebook.py#L104

**Comment by senecameeks** [comment]
Thanks @NoureldinYosri for the catch! 

#6485 exposes `authenticate_user`, which I've added to this start notebook. 
In the case where `get_engine` throws an exception, it will default to a virtual engine instance using `get_qcs_notebook_objects`. Note that because `virtual` is set to True, it does not print the erroneous message `Using processor: ` which was the impetus for this change (See #6427).

**Review by wcourtney — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
