### PR TITLE
Remove deprecated qubits in contrib graphdevice.

### PR DESCRIPTION
**Pull request by MichaelBroughton**

### CODE REVIEW

**Comment by pavoljuhas** [comment]
Perhaps this one needs to be replaces with `device.qubits` ?

https://github.com/quantumlib/Cirq/blob/640ef8f82d6a56ec95361388ce7976e096cca906/docs/tutorials/google/identifying_hardware_changes.ipynb#L286-L290

**Review by pavoljuhas — CHANGES_REQUESTED** [review]
Please check this qubit_set() use in a notebook - 

https://github.com/quantumlib/Cirq/blob/640ef8f82d6a56ec95361388ce7976e096cca906/docs/tutorials/google/identifying_hardware_changes.ipynb#L286-L290

**Comment by MichaelBroughton** [comment]
Ahhhh that's a good catch Pavol! When I went back to try and fix that tutorial I ran into a lot of problems, after fixing the use of `XmonDevice` and `qubit_set` I also saw that none of our QCS devices are calibrated with ISWAP anymore and even worse none of them are reporting two qubit metrics we can use for XEB. Perhaps we should merge this now and open an issue to fix up this tutorial seperately (it is currently in a pretty broken state). WDYT ?

**Review by pavoljuhas — APPROVED** [review]
LGTM

**Pull request merged**
