### PR TITLE
Made the table conforming to rst syntax (should resolve #1185)

### LINKED ISSUE #1185: Make the table in cirq.SimulationTrialResult's doc string render as a table on readthedocs

### PR DESCRIPTION
**Pull request by Ashalynd**

### CODE REVIEW

**Comment by Ashalynd** [comment]
Hmm. On MacOS, sphinx-doc generates multiple errors because it thinks that test files cannot see modules they use, e.g.:

```
WARNING: [autosummary] failed to import 'cirq.AmplitudeDampingChannel': no module named cirq.AmplitudeDampingChannel
WARNING: [autosummary] failed to import 'cirq.AsymmetricDepolarizingChannel': no module named cirq.AsymmetricDepolarizingChannel
...
```

**Comment by Strilanc** [comment]
We could omit the test files. But I'm very surprised this detail differs between linux and mac... are you running in a python 3 environment?

**Comment by Ashalynd** [comment]
Yep, that might be the case. I have a bit funky setup new (new machine), which means Python 2 by default, and Python3 installed with brew.

**Comment by Ashalynd** [comment]
Better, got different errors now :D
```
reading sources... [100%] tutorial                                                                                                                                                                                     
/usr/local/google/home/ashalynd/cirq/docs/api.rst:434: WARNING: failed to import contrib.tpu
/usr/local/google/home/ashalynd/cirq/docs/api.rst:434: WARNING: toctree references unknown document 'generated/contrib.tpu'
/usr/local/google/home/ashalynd/cirq/cirq/google/sim/xmon_simulator.py:docstring of cirq.google.XmonStepResult.sample:5: WARNING: Inline substitution_reference start-string without end-string.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] tutorial                                                                                                                                                                                      
/usr/local/google/home/ashalynd/cirq/docs/api.rst:442:<autosummary>:: WARNING: toctree contains reference to nonexisting document 'generated/contrib.tpu'
b'<partial node>':: WARNING: toctree contains reference to nonexisting document 'generated/contrib.tpu'
b'<partial node>':: WARNING: toctree contains reference to nonexisting document 'generated/contrib.tpu'
(wall of similar errors)
```
Missing files somewhere? I had a fresh checkout.

**Comment by Strilanc** [comment]
There's an open issue to figure out the tpu problem.

**Comment by Ashalynd** [comment]
Yep, verified that it's working.

**Comment by Ashalynd** [comment]
It's not yet rendering super nicely (not sure why) but at least it's rendered as a table.

**Comment by Strilanc** [comment]
Could you include a screenshot?

**Comment by Ashalynd** [comment]
screenshot from 2018-12-06 22-04-01

**Pull request merged**
