### PR TITLE
GridDeviceMetadata: allow qubit pairs in both directions

### LINKED ISSUE #5169: GridDeviceMetadata: qubit ordering within a pair
**Description of the issue**
Today `GridDeviceMetadata` always stores `qubit_pairs` such that the left <= right (lexicographically) in a pair, so the pair `(right, left)` is not in `GridDeviceMetadata.qubit_pairs`.

Is this intended behavior? AFAIU the `DeviceSpecification` proto doesn't guarantee an ordering within a qubit target. The caller could sort the pair before checking against `qubit_pairs`, in which case the fix is a docstring change for `qubit_pairs`. Or alternatively `qubit_pairs` can be implemented with a special set that accepts pairs in both directions.

**How to reproduce the issue**
Flip one of the qubits [here](https://github.com/quantumlib/Cirq/blob/f5d8cfb9443907ba47ce7665f418d3231bbe6f1b/cirq-google/cirq_google/devices/serializable_device_test.py#L55) and rerun the test.

**Cirq version**
0.14

@MichaelBroughton

### PR DESCRIPTION
**Pull request by verult**
Fixes #5169

@MichaelBroughton do you think this API makes sense?

### CODE REVIEW

**Comment by MichaelBroughton** [comment]
This looks good. We are already sorting QIDs here as per @dstrain115 's comment in the issue (so things like serialization are not order dependent). Since this change is happening in the subtype and not the parent type (DeviceMetadata), how would we feel about just adding the `(r, l)` pairs in the tuple to go along with the exsiting `(l, r)` pairs in sorted order ? We wouldn't have to introduce a new type and it would keep things a little simpler.

**Comment by verult** [comment]
Discussed offline. Will instead use a `FrozenSet[Frozenset[cirq.Qid]]` to represent a collection of qubit pairs, similar to the deprecated [SymmetricalQidPair](https://quantumai.google/reference/python/cirq/devices/SymmetricalQidPair) but keeping it simple by using a frozenset.

**Comment by verult** [comment]
Pushed the latest changes. I opted to keep the `qubit_pairs` in the constructor as a `Frozenset[Tuple[Qid, Qid]]` to enforce the requirement that the pair must have exactly 2 elements, and since ordering doesn't matter in the constructor, using the pair as a frozenset isn't necessary.

My preference is to reuse the `SymmetricalQidPairs` which is being deprecated and removed in #5290, which:
* Requires that the pair has exactly 2 elements, unlike a bare frozenset
* Better describes the intention of the data structure for the pair.
In this case we could use `SymmetricalQidPairs` in the constructor as well.

**Review by MichaelBroughton — APPROVED** [review]
LGTM

**Pull request merged**
