### PR TITLE
TrialResult.measurements typo fix

### PR DESCRIPTION
**Pull request by mpharrigan**
How did this pass tests?

### CODE REVIEW

**Comment by mpharrigan** [comment]
maybe `to_list` was added in a more recent version of pandas than the one I've got?

**Comment by mpharrigan** [comment]
yes, It was added on 0.24.0 and I have 0.23.4

**Comment by Strilanc** [comment]
Add a minimum version to the pandas line in requirements.txt

**Comment by mpharrigan** [comment]
This seems to be subsumed by other changes to TrialResult

**Pull request closed without merging**
