### PR TITLE
Add / improve CircuitOperation memoizing

### PR DESCRIPTION
**Pull request by daxfohl**
@95-martin-orion Small change to cache control keys in circuit operations

### CODE REVIEW

**Comment by 95-martin-orion** [comment]
Where would we use this that could not benefit from manually saving a copy of the `mapped_circuit` output? I ask because this makes `CircuitOperation` a _very_ heavy object to carry around - especially since nested `CircuitOperation`s may also have cached copies of their `mapped_circuit`s...

**Comment by daxfohl** [comment]
@95-martin-orion It would save time when you append the same subcircuit to a circuit multiple times, since that uses subcircuit.control_keys to place it correctly (only once per append, not once per moment check, so it's only relevant if you append the same subcircuit multiple times). And I figured since the calculation of control_keys uses mapped_circuit(), caching the result of mapped_circuit would avoid needing to redo that during simulation. 

However, if a subcircuit is only appended once to a circuit, and the circuit isn't used in simulation, this isn't a particularly useful optimization. I wasn't expecting subcircuits to be so large or with so many reps that carrying around an unrolled one would be notably heavy, but don't have any specific insight there.

Anyway, I'm by no means married to it. If you have reservations then it probably makes sense to pass on this one.

**Comment by 95-martin-orion** [comment]
> It would save time when you append the same subcircuit to a circuit multiple times, since that uses subcircuit.control_keys to place it correctly (...)

It sounds like memoizing `control_keys` would be sufficient for this. Could we keep that and drop the `mapped_circuit` memoization?

**Comment by daxfohl** [comment]
@95-martin-orion This is done, just caching control keys now.

**Review by 95-martin-orion — APPROVED** [review]

**Pull request merged**
