### PR TITLE
Add `NOISE_MODEL_LIKE`

### PR DESCRIPTION
**Pull request by Strilanc**
- A `cirq.NOISE_MODEL_LIKE` is a `cirq.NoiseModel`, `None`, or a single-qubit gate
- Methods that took `cirq.NoiseModel` now take `cirq.NOISE_MODEL_LIKE`
- None is auto-converted into `cirq.NO_NOISE`
- Single qubit gates auto-converted into `cirq.ConstantQubitNoiseModel`

For example, you can now say: `cirq.sample(circuit, noise=cirq.depolarize(0.01))`

Part of https://github.com/quantumlib/Cirq/issues/2176

### CODE REVIEW

**Comment by mpharrigan** [comment]
Does switching the order change simulation results?

**Comment by Strilanc** [comment]
Yes, it can change simulation results. For example, for the circuit "X then measure", it means there is two hits of depolarizing noise instead of one before the measurement.

**Comment by mpharrigan** [comment]
I'd consider this a [BREAKING CHANGE] and a particularly insidious one at that. Numerical studies will silently start giving different results when re-run on a newer cirq

**Comment by Strilanc** [comment]
I've reverted the ordering change. Now only contains the generalization of things accepted as noise.

**Pull request merged**
