### PR TITLE
Add seed to simulators

### PR DESCRIPTION
**Pull request by dabacon**
My only worry is that changing seeds between calls on numpy can bork things.

### CODE REVIEW

**Comment by vtomole** [comment]
What do you mean by `bork`?

**Comment by dabacon** [comment]
https://www.merriam-webster.com/dictionary/bork  "to cause (something, such as an electronic device) to stop working properly"   So was just saying that someone could mess with numpy in between calls to the simulator (especially step) and cause issue (either by calling for more random numbers or less likely setting the seed).

**Comment by dabacon** [comment]
Fixed #159

**Comment by mpharrigan** [comment]
I really like allowing the user to pass in a `np.random.RandomState` object so the user has complete control over the sequence of random numbers.

```python
class Simulator:
  def __init__(self, things, rs=None):
    if not isinstance(rs, np.random.RandomState):
      rs = np.random.RandomState(rs)
    self.rs = rs

  def simulate(self):
    i = self.rs.uniform(size=(10,3))
    ...
```

By default, this will seed according to dev/urandom *or* let you pass an integer seed *or* let you share a `RandomState` instantiation

```python
def main():
  my_rs = np.random.RandomState()
  simulator = Simulator(rs=my_rs)
  measurements = simulator.simulate() #  advances the random state
  my_rs.shuffle(measurements)  # uses the same (advanced) random state
  second_measurements = simulator.simulate() 
```

is completely reproducible

**Comment by dabacon** [comment]
Good suggestion.  Create #2020

**Pull request merged**
