### PR TITLE
Remove execution result from notebooks

### PR DESCRIPTION
**Pull request by dabacon**
This removes execution results from notebooks.

@MichaelBroughton these are causing downstream failure with docs build.  Where do I figure out if these are being built when we push these out?  i.e. I'm not certain that the azure notebooks get built with results and don't want to strip these results if this actually isn't built.

### CODE REVIEW

**Comment by dstrain115** [comment]
Are we sure that this example will run in devsite?   I seem to recall that we saved outputs on the azure notebook to avoid trying to execute it during CI

**Comment by dabacon** [comment]
> Are we sure that this example will run in devsite? I seem to recall that we saved outputs on the azure notebook to avoid trying to execute it during CI

That was the question I asked @MichaelBroughton .  Where do we find excluded notebooks?

**Comment by dabacon** [comment]
I take it from your comment @dstrain115 that if it has executed code it doesn't execute it during the CI?  Seems very fragile to me. 

I'll remove Azure and IonQ as I think those are likely to need the executed code.

**Comment by dstrain115** [comment]
Yes, if we store executed results, they are not executed in dev site.

**Comment by dabacon** [comment]
I've removed the notebooks that talk to services.

**Comment by dabacon** [comment]
CirqBot you are bad at judging size.

**Comment by dabacon** [comment]
Filing #5463 to decide about ion device notebook

**Pull request merged**
