### PR TITLE
Make test ordering and parametrization reproducible

### PR DESCRIPTION
**Pull request by pavoljuhas**
Implement deterministic ordering of pytest parameters.
Add CIRQ_TESTING_RANDOM_SEED environment variable for seeding
random numbers generation in random and numpy.random modules.
Use commit epoch time as the default seed to have a non-constant,
but deterministic seeding.

NB: Use empty CIRQ_TESTING_RANDOM_SEED to prevent seeding, for example,
    CIRQ_TESTING_RANDOM_SEED="" check/pytest

This implements https://github.com/quantumlib/Cirq/issues/4787

### CODE REVIEW

**Review by MichaelBroughton — APPROVED** [review]
LGTM

**Comment by vtomole** [comment]
We can also use [pytest-randomly](https://pypi.org/project/pytest-randomly/) to get random a seed but it will also come with other stuff; like running the tests in random order, so I'm fine with this.

**Comment by vtomole** [comment]
Oh, we can pass in the `--randomly-dont-reorganize` flag. But on the other hand, `pytest-randomly` will be a new dependency we add to Cirq's dev tools on top of the already enormous list of dev tool packages we have..

**Review by vtomole — CHANGES_REQUESTED** [review]
Let's add `export CIRQ_TESTING_RANDOM_SEED` to the incremental coverage checks as well.

**Comment by pavoljuhas** [comment]
> Let's add export CIRQ_TESTING_RANDOM_SEED to the incremental coverage checks as well.

The incremental-coverage scripts run tests with `check/pytest` which already exports CIRQ_TESTING_RANDOM_SEED:

- https://github.com/quantumlib/Cirq/blob/894d49e0a75eb81d29c1b83c6177a488c1797dd9/check/pytest-and-incremental-coverage#L57
- https://github.com/quantumlib/Cirq/blob/894d49e0a75eb81d29c1b83c6177a488c1797dd9/check/pytest-changed-files-and-incremental-coverage#L93

Is there perhaps some other script that I am missing?

**Review by vtomole — COMMENTED** [review]
Ah, okay.

If you have the time to try `pytest-randomly`, please do. In the `conftest.py`, we can have

```python
@pytest.fixture()
def global_seed(pytestconfig) -> int:
    return pytestconfig.getoption("randomly_seed")
```

This will shave a lot of code in this PR with the caveat of us adding `pytest-randomly` as a Dev tools dependency.

**Comment by pavoljuhas** [comment]
> If you have the time to try pytest-randomly, please do. 

They have a wontfix issue https://github.com/pytest-dev/pytest-randomly/issues/75 which implies that having random parameters in `@pytest.mark.parametrize` (random at import time) breaks distributed run with pytest-xdist.
That is just the use case I'd like to support here as Cirq has a number of such parametrizations, for example, https://github.com/quantumlib/Cirq/blob/894d49e0a75eb81d29c1b83c6177a488c1797dd9/cirq-core/cirq/testing/random_circuit_test.py#L95

Resetting random seed for every test case as done in pytest-randomly sounds fishy, because every test then gets the same handful of random numbers from the start of a seeded RNG sequence.

On the other hand, the randomized test order with pytest-randomly sounds useful provided it indeed works with python-xdist.
@vtomole - perhaps that should be opened as a separate issue?

**Comment by pavoljuhas** [comment]
@vtomole - please let me know if there are still some changes required here.

**Comment by vtomole** [comment]
@pavoljuhas Thanks for the ping. I missed the first notification. I'll finish reviewing this today.

**Review by vtomole — APPROVED** [review]
LGTM.

**Comment by vtomole** [comment]
> which implies that having random parameters in @pytest.mark.parametrize (random at import time) breaks distributed run with pytest-xdist.

Okay. Thanks for looking into it.

**Pull request merged**
