### PR TITLE
Fix for property override for `num_qubits()` method

### PR DESCRIPTION
**Pull request by paniash**
Fixes issue #4185.

NOTE: Breaks changes.

### CODE REVIEW

**Review by viathor — APPROVED** [review]

**Comment by balopat** [comment]
Thanks @paniash - 

Feedback: 

1. The PR description: "NOTE: Breaks changes." doesn't explain much, and typically it is the changes that break functionality in existing user code (not the other way around). Can you think of a better way to explain which users might be affected, what they should do to upgrade their code to the new version? 

2. We almost never accept code changes without adding tests. Please add unit tests as needed and ensure that `check/pytest` succeeds (`check/pytest-changed-files` is a faster version that only checks changed files).

**Review by viathor — CHANGES_REQUESTED** [review]
Thanks for catching this, @balopat !

Regarding tests, I suggest to add a test helper function which checks that a channel has the appropriate interface and then use it in tests for all channels, or at least those defined in common_channels.py. The test should fail before this change and succeed after it. Also, this will prevent similar bugs affecting other channels in future.

**Comment by balopat** [comment]
friendly ping @paniash - can you please fix the comments above? Thanks!

**Comment by paniash** [comment]
@balopat Sorry about the delay. I'm currently busy with my finals. I'd love to work on this but if it's urgent, please feel free to work on this issue and close my PR.

**Comment by balopat** [comment]
> @balopat Sorry about the delay. I'm currently busy with my finals. I'd love to work on this but if it's urgent, please feel free to work on this issue and close my PR.

Good luck with your finals! There is zero urgency around this, you can pick it up after your finals.

**Comment by dabacon** [comment]
Hi @paniash Thanks for working on this. I grabbed this and completed the test so that we have this fix in for the next release.  Sorry to have jumped the line but definitely finals are more important :)

**Comment by dabacon** [comment]
Fixed in #4652

**Pull request closed without merging**
