### PR TITLE
Remove XMON as engine default

### PR DESCRIPTION
**Pull request by dstrain115**
- Engine now raises ValueError if you don't specify gate_set.
- While technically backwards incompatible, I don't think anyone
will have working code that doesn't specify a gate_set here.

Solves #2957

### CODE REVIEW

**Comment by dstrain115** [comment]
> We should somehow add this to a "breaking changes" list that we can point out in the next release. We could add a "staging" area for release notes for the next planned minor release where we can build up these deprecation notices.

I will leave that up to a later PR, since we don't yet have a current place to put that.  If you have a suggestion on where to add it, I can put up a PR to add a first draft of the "upcoming release" notes.

**Comment by dabacon** [comment]
I guess the question is why have a default if you have to specify it now?

**Comment by dstrain115** [comment]
> I guess the question is why have a default if you have to specify it now?

I am not sure I understand the question.  Do you mean: why have a default of `None`?  I think we need that in order to make it a named parameter instead a positional parameter.

**Comment by balopat** [comment]
> > We should somehow add this to a "breaking changes" list that we can point out in the next release. We could add a "staging" area for release notes for the next planned minor release where we can build up these deprecation notices.
> 
> I will leave that up to a later PR, since we don't yet have a current place to put that. If you have a suggestion on where to add it, I can put up a PR to add a first draft of the "upcoming release" notes.

Sounds good - this is my suggestion - https://github.com/quantumlib/Cirq/issues/3143 - as soon as I'll get around it, I'll create it.

**Pull request merged**
