### PR TITLE
Remove python3.9 from CI tests

### PR DESCRIPTION
**Pull request by NoureldinYosri**
first step towards dropping py3.9 in cirq1.4 https://github.com/quantumlib/Cirq/issues/6463

### CODE REVIEW

**Comment by pavoljuhas** [comment]
Is everyone OK with removing the CI status checks for 3.9 (Python Ubuntu (3.9) etc.) in the repo settings now?
I can do so tomorrow unless there are objections.

**Comment by pavoljuhas** [comment]
@NoureldinYosri - there are few more places that I think can be bumped to 3.10 now, see below.  Otherwise, LGTM.
```
.github/workflows/release-main.yml:18:          python-version: '3.9'
asv.conf.json:11:    "pythons": ["3.9"],
docs/dev/development.md:97:    Make sure you have python 3.9 or greater.
docs/start/install.md:15:Cirq currently supports python 3.9 and later.
docs/start/install.md:23:0. Make sure you have python 3.9.0 or greater.
docs/start/install.md:90:0. Make sure you have python 3.9.0 or greater.
docs/start/install.md:157:1. Make sure you have python 3.9.0 or greater.
release.md:85:System requirements: Linux, python3.9
```

**Comment by NoureldinYosri** [comment]
@pavoljuhas I updated the requested files, ptal

**Comment by NoureldinYosri** [comment]
@pavoljuhas I changed the branch protection rule to be for 3.10 rather than 3.9

**Comment by pavoljuhas** [comment]
> @pavoljuhas I changed the branch protection rule to be for 3.10 rather than 3.9

Did the same right now.  Can you please push an empty commit to restart the CI?

**Pull request merged**
