### PR TITLE
XEB: Add option to specify qubits

### PR DESCRIPTION
**Pull request by eliottrosenberg**
Based on user feedback, adding the option to specify which qubits to run parallel XEB on.

### CODE REVIEW

**Comment by NoureldinYosri** [comment]
I already added that in https://github.com/quantumlib/Cirq/pull/6455

**Comment by eliottrosenberg** [comment]
Great, thanks!

**Comment by eliottrosenberg** [comment]
We can close this one once that one gets merged then.

**Comment by NoureldinYosri** [comment]
superseded by https://github.com/quantumlib/Cirq/pull/6455

**Pull request closed without merging**
