### PR TITLE
Minimum required version of quimb.

### PR DESCRIPTION
**Pull request by mpharrigan**
Alternatively, you can comment out `state_vector.py` line 150.

Fixes gh-3263

### CODE REVIEW

**Comment by dstrain115** [comment]
Ideally, I would like to support quimb 1.2 if possible, since a certain repo ending in "3" has that version.  (Either that, or we need to upgrade 1.3)

**Comment by balopat** [comment]
It feels odd to have a constraint on our contrib by g3 and vica versa. Can we make our optional package optional in g3 as well?

**Comment by dstrain115** [comment]
> It feels odd to have a constraint on our contrib by g3 and vica versa. Can we make our optional package optional in g3 as well?

Yeah, it's not a hard constraint.  I don't know if there are optional requirements in g3 (the tests fail for quimb 1.2, so it would be tough to detect correctly).  There are work-arounds, but stuff like this always sets off warning bells for me.  The more restrictive our requirements, the harder it will be to install.  If there is a legitimate requirement that we need, that's fine.  However, if it is just because we are lazy, then we are pushing the work off on someone else (me and everyone else who installs this package on an older system).  It's not just Google either.  Many bigger systems, like national labs, for instance, have standardized environments where they try to keep a set of packages that will work for scientific software.

For quimb (in contrib) though, it's not really that big of a deal, so if the requirement is 1.3, I guess I'll deal with it.  It looks like quimb 1.2 is already over a year old, so 1.3 is probably not too unreasonable.

Since we know which line causes the issue, can we just do a quick compatibility check on that line and skip it (maybe with a warning) if the version is old?  That would be more user friendly than forcing an upgrade to the newest version.

**Comment by mpharrigan** [comment]
Yeah, I could add a conditional skip of that line. Maybe we could solicit a community contribution to do a little investigation to figure out if that line is necessary or not.

**Comment by balopat** [comment]
Great points @dstrain115, this is an ever green tension - users have a wide range of versions of our dependencies, however the wider version range we support the larger the cost to maintain it. 

We should definitely do our due diligence respectfully and not take it lightly (we shouldn't be lazy about it) to limit our versions. 

We _know_ that it works on quimb 1.3.0 and quimb provides advantage over the DensityMatrixSimulator in some cases, which was the primary reason to introduce this feature. 

The complete investigation for this particular failure is going to take some time, as one would have to test whether there are cases where removing this line (and using quimb 1.2.0, which might bring other degradations!) is going to cause performance degradation and whether that nullifies the advantage or not. The functionality will still work, the performance is not guaranteed, only on 1.3.0. 

I don't think I want to burn engineer work on exploring the performance guarantees of a year old system. 

Thus, my recommendation: 
- let's try to keep quimb unrestricted, 
- add a conditional skip on the line AND print a warning that performance is not guaranteed, things might be slower than expected, we recommend upgrading to the latest quimb version 

How does that sound?

**Comment by mpharrigan** [comment]
done

**Pull request merged**
