### PR TITLE
Add missing-raises-doc rule to the linter and subsequent refactor.

### PR DESCRIPTION
**Pull request by thanacles**
This is associated to issue #3388

### CODE REVIEW

**Review by balopat — APPROVED** [review]
LGTM

**Comment by thanacles** [comment]
@balopat Fixed the merge conflicts and a few places where problem pydocs where added since this PR was formed.  I feel like we only have a small window before this PR will further merge conflicts and lint violations.

**Review by balopat — APPROVED** [review]

**Comment by balopat** [comment]
Agreed, let's do it!

**Comment by mpharrigan** [comment]
I think this change adds more developer overhead than value it provides. I've rarely seen exceptions documented this way in Python. It's usually very clear what has happened when an exception is raised because of the message. If it's not, we should fix the message and not the docstring.

**Comment by thanacles** [comment]
@mpharrigan I agree it adds more developer overhead, and it would be hard for me to show how much value it provides.  However, I don't think this is for helping people who are getting the error. This is for people to know what can happen when calling the function, so that they can prevent ever getting the error in the first place.  That said, I recognize it is a judgement call whether it should be implemented.  This commit was called for by bug #3388 , so that bug should be changed if you don't want more commits like this.

**Pull request merged**
