### PR TITLE
[Obs] 4.4 - Readout error mitigation

### PR DESCRIPTION
**Pull request by mpharrigan**
Add a facility to take readout calibrations by measuring the <Z> observables under the empty circuit with readout symmetrization turned on. This can be plumbed through so other observables measured with `measure_observables` can be corrected. Note that this all only works for symmetric readout error enforced through readout_symmetrization.

Part of #3647

### CODE REVIEW

**Comment by mpharrigan** [comment]
Do we have an asymmetric readout channel available in non-contrib cirq? I'd like to keep that in my test

**Comment by 95-martin-orion** [comment]
> Do we have an asymmetric readout channel available in non-contrib cirq? I'd like to keep that in my test

Meaning a noise model like `DepolarizingWithDampedReadoutNoiseModel`? AFAIK all of those are either in contrib or in cirq_google (e.g. the [per-qubit version](https://github.com/quantumlib/Cirq/blob/16dd1bb210e930803efce4cdd32acfa7035a563f/cirq-google/cirq_google/experimental/noise_models/noise_models.py#L23)). I wouldn't object to moving them to cirq-core, though.

I'm not sure what "asymmetric readout" means here, but you may be able to get something similar either with [`from_noise_model_like`](https://github.com/quantumlib/Cirq/blob/16dd1bb210e930803efce4cdd32acfa7035a563f/cirq-core/cirq/devices/noise_model.py#L42) or by creating your own noise model:
```python
# Simple model that adds amplitude damping after each moment
model_1 = cirq.NoiseModel.from_noise_model_like(cirq.amplitude_damp(0.1))

# More complex model that adds bitflips before measurement
class ReadoutErrorModel(cirq.NoiseModel):
    def noisy_operation(self, op):
        if isinstance(op.gate, MeasurementGate):
            return [cirq.bit_flip(0.1), op]
        return op
```

**Comment by mpharrigan** [comment]
asymmetric: p00 != p11

**Comment by 95-martin-orion** [comment]
> asymmetric: p00 != p11

In that case, the `model_1` example above would fit your requirements, although it may require some finagling to fit your test.

**Comment by mpharrigan** [comment]
vendored a noise model in the test, ptal

**Review by 95-martin-orion — APPROVED** [review]

**Pull request merged**
