### PR TITLE
Fix links in github view

### PR DESCRIPTION
**Pull request by dstrain115**
- Change .md links to .ipynb links.
- From local building the docs, this _should_ work in readthedocs as well.

Closes: https://github.com/quantumlib/Cirq/issues/2887

### CODE REVIEW

**Comment by dstrain115** [comment]
> Can we fix the link to that's linked under `serialization guidelines` in https://github.com/quantumlib/Cirq/blob/master/docs/dev/gates.md while we are at it?

Changed to relative link.  That should fix it in github as well as readthedocs I think.

**Comment by vtomole** [comment]
@dstrain115 I get `Unknown type` when i click on the `noise.ipynb` link. Are you getting this?

**Comment by vtomole** [comment]
I'm also getting it or `qudits.ipynb`

**Comment by dstrain115** [comment]
> I get `Unknown type` when i click on the `noise.ipynb` link. Are you getting this?

I am not getting that.  Can you tell me the steps you are doing to get that error?

**Comment by m-pedro** [comment]
The Examples link under "Next Steps" in the Cirq Tutorial is broken: https://github.com/quantumlib/Cirq/blob/master/docs/tutorial.ipynb. 
It should point here:
https://github.com/quantumlib/Cirq/tree/1daad398783964cc9b1965ae957812b5ca1f1395/examples

**Pull request merged**
