### PR TITLE
DeviceSpecification serialization approach

### PR DESCRIPTION
**Pull request by verult**
While DeviceSpecification serialization happens on the server side, the serialization logic should exist close to the deserialization logic to keep them consistent. This PR has 3 proposals of laying out the serialization logic:
* (preferred) A function in the same file as `GoogleDevice` (renamed to `GridDevice` in the latest iteration) taking as input only the essential information (i.e. qubits, qubit pairs, gateset, gate_duration) to construct a `DeviceSpecification` message.
* A function in the same place, but takes in a `GridDeviceMetadata` instead.
* A `GridDevice` method which serializes the underlying `GridDeviceMetadata` as `DeviceSpecification`.

I prefer the first solution because, while it's tempting to have the symmetry of being able to both serialize and deserialize a `GridDevice`, `GridDevice` and `GridDeviceMetadata` are designed as client-side *views* rather than *models* in MVC terms, and these views contain more information than the underlying model (i.e. compilation target gatesets, generated equivalence GateFamilies like `FSimGateFamily`). Serializing `GridDeviceMetadata` to `DeviceSpecification` means we'll have to construct `GridDeviceMetadata` with less information than it was designed to have.

@dstrain115 @tanujkhattar WDYT? Also cc @maffoo @wcourtney FYI

Please ignore the first commit (that's only there because #5203 hasn't merged yet).

### CODE REVIEW

**Comment by dstrain115** [comment]
As discussed in our call, I agree with the preferred method, though I think we should have "alternative 2" as an interface to turn GoogleDevice to a proto if necessary (that can, in turn call to_proto).  This could be called to_device_specification() or something to indicate that it is stripping out some metadata (and this can also be clarified in the docstring)

**Comment by verult** [comment]
I'm a bit hesitant to include alternative 2 which would encourage a misuse of GridDevice IMO. If this path exists, it will likely become the most commonly used path since it seems convenient to simply construct a GridDevice on server side and serialize that. We could perhaps add it later on instead if it's deemed necessary.

**Comment by dstrain115** [comment]
> If this path exists, it will likely become the most commonly used path since it seems convenient to simply construct a GridDevice on server side and serialize that.

Why is this a problem?  This seems like a perfectly reasonable path to me.

**Comment by verult** [comment]
Having that as the main path is tricky because it's unclear which fields in `GridDeviceMetadata` needs to be set on server side when instantiating `GridDevice` by looking at the `GridDevice` API. We could add comments, but ideally it should be clear from the serialization API what's the minimum information sufficient to serialize to `DeviceSpecification`.

If `GridDeviceMetadata` has a clear split in the API between a server-provided part and a client-generated part, then having `GridDevice` serialization as the main path sgtm, but IMO this complicates the client API and results from forcing a coupling between server-side (model) and client-side (view) requirements.

On the other hand, having it as a convenient method to turn a `GridDevice` back into a `DeviceSpecification` on Cirq client side I think makes sense. We could also instead just store the full `DeviceSpecification` as a `GridDevice` field rather than doing a serialization. This bypasses the need to have logic that identifies what needs to be stripped, and this logic may need to be updated in the future.

**Comment by verult** [comment]
Synced with @dstrain115 offline. Doug raised the point that on server side, incoming programs need to be validated against the device (for example, programs may target the wrong qubits), and it would be ideal to construct `GridDevice` on server side anyway for that purpose anyway, in which case `GridDevice.to_proto()` would be convenient.

For MVP, let's move forward with the separate `to_proto(qubits, qubit_pairs, gateset, gate_durations)` for now. There will be some refactoring on server side to address other issues anyway, which would be a good opportunity to address this as well.

Will close this PR and open a separate one for serialization implementation.

**Pull request closed without merging**
