### PR TITLE
Rewriting `np.dot` and `np.transpose` in `cirq.linalg.predicates.py`

### PR DESCRIPTION
**Pull request by renatomello**
This proposed minor changes would allow these functions to be compatible with `EagerTensor` inputs, since `EagerTensor`s do not have `.dot` and `.T` as attributes.

This is important in and of itself, but also important for intergration of `Cirq` with [`Qibo`](https://github.com/qiboteam/qibo) SDK, which uses `TensorFlow` as one of its backends.

### CODE REVIEW

**Comment by renatomello** [comment]
I've already signed up the CLA with the right email and github username, but it's not showing up here yet

**Comment by vtomole** [comment]
> This proposed minor changes would allow these functions to be compatible with `EagerTensor` inputs

This change doesn't seem to break anything so that's good. On the other hand, these functions are type annotated to take `np.ndarray` as inputs not EagerTensor. What's wrong with passing in `EagerTensor.numpy()` to these functions?

Can you post as snippet that passes `EagerTensor` as inputs?

**Review by viathor — COMMENTED** [review]
I agree with @vtomole that passing `EagerTensor.numpy()` seems more appropriate.

Also, I'd like to point out that if this PR is accepted, then it should come with a unit test. Otherwise, it's too easy to accidentally undo it.

**Comment by renatomello** [comment]
This is not necessary for the `Qibo` project anymore, so I'm going to close it. Thanks for the comments though.

**Pull request closed without merging**
