### PR TITLE
Define cirq.run/run_sweep/NoiseModel/NO_NOISE/ConstantQubitNoiseMode

### PR DESCRIPTION
**Pull request by Strilanc**
- `cirq.NoiseModel` has semi-abstract noisy_moment/moments/operation methods (at least one must be implemented)
- `cirq.ConstantQubitNoiseModel` applies a given gate to every qubit at the end of every moment
- `cirq.NO_NOISE` is a noise model that returns its inputs unchanged
- `cirq.run`/`cirq.run_sweep` delegates to an appropriate simulator by analyzing their input
- `DensityMatrixSimulator` now has a `noise` attribute that takes a `NoiseModel`
- Simulators now force keyword args for `dtype`

Part of https://github.com/quantumlib/Cirq/issues/1355
Fixes https://github.com/quantumlib/Cirq/issues/343

### CODE REVIEW

**Comment by Strilanc** [comment]
Please make comments on the design. Is this a reasonable way to define noise?

**Comment by peterse** [comment]
I agree w Dave  - I think it would be useful for the NoiseModel to be applied before running the simulator so that the user could access the modified circuit (and we'd likely end up writing such a noise wrapper in our external library if its not available at the cirq level). 

I do like the flexibility in the NoiseModel though. One use we have for noise is to apply channels conditionally on gate type, e.g. greater damping for 2-qubit gates, as an ad hoc way of modelling gate fidelity. So the generality for the NoiseModel is nice in that respect

**Comment by Strilanc** [comment]
> I worry a bit that we are again putting into the simulators transformations on the circuit. Of course the user has to supply the noise model, so that is good (better than decompose, which is hidden). But note that the user here cannot even see what the noisy circuit that they just ran looks like.

The fact that the user explicitly asks for the noise should make it not confusing. I think that was the main downside of automatic decomposition.

I agree that we should have a way to spit out the noisy circuit so the user can inspect it. Especially if the noise model is randomly inserting gates, instead of deterministically inserting channels. Perhaps we could include the simulated moment operations in the TrialResult?

**Comment by Strilanc** [comment]
> I worry a bit about cirq.run because what about engine?

I was picturing an argument like `service` or similar that defaults to local simulation. I think local simulation is the right default.

**Comment by dabacon** [comment]
> I was picturing an argument like `service` or similar that defaults to local simulation. I think local simulation is the right default.

I

**Comment by Strilanc** [comment]
@dabacon Did you accidentally hit the close button while typing?

**Pull request closed without merging**
