### PR TITLE
Channel matrix -> superoperator

### PR DESCRIPTION
**Pull request by viathor**
Implements results of [this vote](https://github.com/quantumlib/Cirq/issues/4179#issuecomment-892898319). The vote will also affect the name of the corresponding protocol, but it is WIP.

### CODE REVIEW

**Review by MichaelBroughton — COMMENTED** [review]
These did make it into the previous public release. Do you think it might be worth deprecating the old names too ?

**Comment by viathor** [comment]
PTAL

**Review by MichaelBroughton — APPROVED** [review]
LGTM

**Review by vtomole — COMMENTED** [review]
LGTM

**Pull request merged**
