### PR TITLE
Docs frontmatter and some cleanup

### PR DESCRIPTION
**Pull request by lamberta**
Add frontmatter, buttons, and clean up some notebook structure. Not much for content change.
Using some placeholder URLs for some buttons so will need to make a pass later but that's a search/replace vs adding new notebook cells (rather tedious). This gets the structure in place.

Normalized notebooks with [nbfmt](https://github.com/tensorflow/docs/tree/master/tools/tensorflow_docs/tools):

```
$ python3 -m pip install -U --user git+https://github.com/tensorflow/docs

$ python3 -m tensorflow_docs.tools.nbfmt --indent=1 docs/
```

### CODE REVIEW

**Comment by lamberta** [comment]
cc: @balopat

**Comment by balopat** [comment]
Hi @lamberta - adding in google-colab as requirement is problematic - it's going to break all the python 3.8 builds and totally breaks locally jupyter. I opened https://github.com/quantumlib/Cirq/issues/3368 instead what do you think about using pydata-google-auth?

**Comment by lamberta** [comment]
Hey @balopat ,

Adding `pydata-google-auth` instead is fine by me (I'll revert my last commit). Currently the *Build docs* CI test is failing because the `google.colab` module is used in a few notebooks. Can we get around this?

**Comment by balopat** [comment]
If you allow me to add commits to this PR, I'll also setup a check that will ensure that notebooks are formatted correctly on every PR. I will resolve the authentication blob in a separate PR and then we can rebase this on top of that. 

Alternatively, one way I can see getting around this is to comment out the google colab authentication for now and provide details in the comments...but let me think about this a bit more.

**Comment by balopat** [comment]
> If you allow me to add commits to this PR, I'll also setup a check that will ensure that notebooks are formatted correctly on every PR. I will resolve the authentication blob in a separate PR and then we can rebase this on top of that.
> 
> Alternatively, one way I can see getting around this is to comment out the google colab authentication for now and provide details in the comments...but let me think about this a bit more.

Actually setting `nbsphinx_allow_errors = True` is not the worst. I added a comment to turn error checking back on when we switch over to `pydata_google_auth`.

**Comment by balopat** [comment]
Alright, I think we should be good to go now - the new script actually caught an error in my formatting (https://github.com/quantumlib/Cirq/pull/3393/checks?check_run_id=1215735034) when I used PyCharm to edit my notebook to fix a sphinx warning regarding inconsistent headers. It's working nicely!

**Review by balopat — APPROVED** [review]

**Comment by lamberta** [comment]
Ah, great. Thanks, @balopat !

**Comment by balopat** [comment]
Argh. I'm looking at the last weird error. Will be fixed soon.

**Comment by balopat** [comment]
There are some other issues as well with the transformation logic (it might be related):

image

**Comment by lamberta** [comment]
For the readthedocs pages, can you strip the `<table class=\"tfo-notebook-buttons\" ... </table>` ?

**Comment by balopat** [comment]
> <table class=\"tfo-notebook-buttons\" ... </table>

working on it...

**Pull request merged**
