### PR TITLE
Disallow empty measurement keys and fix tests using empty keys

### PR DESCRIPTION
**Pull request by smitsanghavi**
Part of #4040

### CODE REVIEW

**Comment by smitsanghavi** [comment]
@95-martin-orion

**Comment by 95-martin-orion** [comment]
Discussed offline - this may not be necessary if we choose to auto-convert keyless gates into qubit-named gates. Holding off on merge until @smitsanghavi confirms his decision.

**Comment by balopat** [comment]
ping @95-martin-orion @smitsanghavi is this to be closed or pushed forward?

**Comment by 95-martin-orion** [comment]
Closing this as we had opted for a different solution (auto-convert "keyless" gates to qubit-based naming). If we need to revisit this (or decide that this PR was the correct choice) we can reopen this PR.

**Comment by smitsanghavi** [comment]
Reviving this since we decided to revert the qubit based auto-naming.

**Review by 95-martin-orion — APPROVED** [review]
Looks good to me. IIUC, all `replace` calls go through the constructor, so any accidental clearing of key strings by remapping will be prevented.

**Pull request merged**
