### PR TITLE
insert_into_range updated to preserve moments insertion #1246

### PR DESCRIPTION
**Pull request by iamvamsi**

### CODE REVIEW

**Comment by iamvamsi** [comment]
@Strilanc @kevinsung : Updated the `insert_into_range` as per requirements. I want to get an eye before going further.

**Comment by iamvamsi** [comment]
#1246

**Comment by kevinsung** [comment]
I'm sorry @iamvamsi but I must admit I didn't quite think through what the logic should be for this method. It's possible that "preserving moments" doesn't quite make sense for this method. Can you explain what the behavior of the method is, with your changes?

**Comment by iamvamsi** [comment]
@kevinsung : `insert_into_range` method, with my changes, when encountered a moment would insert it as new moment in the circuit next to the index it is currently in and skips the inserted moment for any future insertions. 
Eg: Lets say we have `Circuit([Moment([cirq.X(x)])] * 4)` and we plan to do `c.insert_into_range([cirq.Y(y), Moment([cirq.Z(y), cirq.Z(x)]), cirq.Y(y)], 2, 4)` the resulting circuit would be 
```
x: ───X───X───X───Z───X───

y: ───────────Y───Z───Y───

```
but lets say we plan to insert `c.insert_into_range([cirq.Y(y), Moment([ cirq.Z(x)]), cirq.Y(y)], 2, 4)` the resulting circuit would be 
```
x: ───X───X───X───Z───X───

y: ───────────Y──────Y───

```
I must say this may not be a very intuitive behaviour and as suggested by you we should discuss the same.

**Comment by kevinsung** [comment]
@iamvamsi if you don't mind I'll close this for now; I think further progress needs to be made on #1246 before proceding with something like this.

**Comment by iamvamsi** [comment]
Thanks.

**Pull request closed without merging**
