### PR TITLE
Easy changes to difficult terminology

### PR DESCRIPTION
**Pull request by mpharrigan**

### CODE REVIEW

**Review by wcourtney — APPROVED** [review]
❤️

**Review by pavoljuhas — APPROVED** [review]

**Comment by nishitkshah** [comment]
Can we mention Quantum Supremacy in brackets? I think it is a highly popular term after the publication of the 53-qubit experiment. IT would be god to keep a mention of it for easy search.

**Comment by rht** [comment]
I think "quantum advantage" is a more searchable term, that has been used in literature, than "beyond-classical".

**Comment by rht** [comment]
Number of results on Google Scholar:
- "beyond classical" has ~25900 results. This is because the term is used in several contexts in other fields. I suppose it doesn't matter to language models because that they could disambiguate based on the surrounding tokens. But it still requires disambiguation.
- "quantum advantage" has 11600 results.
- "quantum supremacy"  has ~10600 results.

**Pull request merged**
