### PR TITLE
Verified and documented methods sampling from Haar measure.

### PR DESCRIPTION
**Pull request by hsim13372**
Fixes https://github.com/quantumlib/Cirq/issues/1451

- Checked to make sure methods in `cirq.testing.linalg` is sampling from the Haar measure.
- Added a few more simple tests in `cirq.testing.linalg.lin_alg_utils_test.py`

### CODE REVIEW

**Comment by kevinsung** [comment]
It looks to me to still be incorrect ...

It seems that the last line of `random_unitary` should actually be
```
    return q * (d / abs(d)) * q
```
and `random_orthogonal` should be the same as `random_unitary` except starting with a real matrix.

**Comment by hsim13372** [comment]
Hmm for the `random_unitary`, I followed the reference by Mezzadri where his version was:

`from scipy import *
def haar_measure(n):
’’’’’’A Random matrix distributed with Haar measure’’’’’’
z = (randn(n,n) + 1j*randn(n,n))/sqrt(2.0)
q,r = linalg.qr(z)
d = diagonal(r)
ph = d/absolute(d)
q = multiply(q,ph,q)
return q`

I believe this scipy `multiply` routine's third argument is for the location into which the result is stored so q = q*ph.

For `random_orthogonal`, I removed the multiplication by `ph = d/absolute(d)` (as is done for the unitary case) because I thought scipy's QR decomposition for a real matrix already ensures that the diagonals of R are positive. I could be wrong though!

**Comment by hsim13372** [comment]
Sorry, I take back the part about assuming positive diagonals for R. It seems like I should multiply by `ph = d/absolute(d)`. @Strilanc, is it possible to add to this pull request, or should I start a new one?

**Comment by Strilanc** [comment]
@hsim13372 You have to create a new pull request.

**Pull request merged**
