### PR TITLE
Add missing `import cirq`

### PR DESCRIPTION
**Pull request by MarkDaoust**
Fix notebook, this is failing in the site import pipeline.

### CODE REVIEW

**Review by vtomole — DISMISSED** [review]
Hey @MarkDaoust, you've added `import cirq` under an `ImportError` exception; which means the exception will be raised again except this time it won't be caught.

**Review by vtomole — COMMENTED** [review]
Opps, I now see that it is installed after the `import` error.

**Review by vtomole — APPROVED** [review]
LGTM

**Review by vtomole — COMMENTED** [review]
One nit: could you move the second import statement down in order to be more consistent with other notebooks like https://github.com/quantumlib/Cirq/blob/master/docs/circuits.ipynb

**Comment by MarkDaoust** [comment]
Done.

**Comment by vtomole** [comment]
Thanks!

**Pull request merged**
