### PR TITLE
Update calibration tutorials

### LINKED ISSUE #3933: Copy docs/tutorial/floquet but for XEB
cc @karlunho @rmlarose 

Request that there be the identical walk-through but for XEB.

### PR DESCRIPTION
**Pull request by rmlarose**
This PR

- Adds a new tutorial on calibration showing basic usage for Floquet and XEB.
- Removes the "simple example" section from the Floquet calibration tutorial because that is now in the previous one.
- Reframes the "advanced calibration tutorial" as an example of using / benchmarking XEB calibration.

So, the result is three tutorials on calibration:

(1) An overview explaining the calibration API at a high level + how to use it.
(2) A detailed example / benchmark of using Floquet calibration (on a linear chain circuit).
(3) A detailed example / benchmark of using XEB calibration (on random circuits).

(3) closes #3933. (It was decided not to use the same linear chain circuit from the Floquet example, but rather a circuit in which XEB is known to perform well on.)

cc @mrwojtek @mpharrigan

### CODE REVIEW

**Comment by rmlarose** [comment]
Hmm.. CI is complaining about [not being able to find advanced_calibration.ipynb](https://github.com/quantumlib/Cirq/pull/4226/checks?check_run_id=2854835120#step:5:320), which is (intentionally) removed in this PR. Do I need to do anything else besides deleting the file? I can't seem to find it referenced anywhere.

I guess it's because the notebook test is comparing to cirq/master which has advanced_calibration.ipynb?

**Comment by tanujkhattar** [comment]
I think `isolated_notebook_test.py` should be updated to ignore running tests for the deleted file. i.e. Replace the `git diff --name-only  {rev}`   with  `git diff --diff-filter=d --name-only {rev}`
https://github.com/quantumlib/Cirq/blob/6af64a27312b326c8284eb950bd17065cf82544a/dev_tools/notebooks/isolated_notebook_test.py#L108

IIUC, the objective is to run the notebook tests only for changed notebooks and we use git diff just to figure out which notebooks changed. Hence, the deleted notebooks should not be considered here.

**Comment by mpharrigan** [comment]
Please feel free to respond with "that would be too difficult, I'm not going to do it" but: how hard would it be to use git-fu to organize this into ~two commits that separates 1) organizational changes where content is only moved around and 2) changes (new content; deleted content; modified content) to the content that can be nicely diffed?

**Comment by rmlarose** [comment]
Yeah, sorry for the large PR. The notebooks do link to each other, but if we're ok with temporary dead links until everything is merged it's no problem. (I'll remove them from book.yaml so they don't show up on the site until everything is in.) 

I'll split this into 2-3 parts.

**Comment by mpharrigan** [comment]
Oh I was thinking you could keep it in one big pull request but organize the pull request as ~2 main commits that I could dig into to see a more meaningful diff. After those, you could add smaller commits as we iterate through the review in the normal way

**Comment by rmlarose** [comment]
Ah, ok. I opened #4258 which does this if I understand you correctly. PTAL.

**Pull request closed without merging**
