### PR TITLE
Require n_rows > 1 in generate_boixo_2018_supremacy_circuits_v2_bristlecone

### LINKED ISSUE #2295: bug in supremacy test circuit
I ran the function
```
generate_boixo_2018_supremacy_circuits_v2_bristlecone(
        n_rows: int, cz_depth: int, seed: int) -> circuits.Circuit
```
in `cirq.experiments.google_v2_supremacy_circuit` with `n_rows = 1` and got trapped in infinite loops.

I think this is because when we have `n_rows = 1`,  `_make_cz_layer` would never return any cz gate, since there's only one qubit, thus in ` _add_cz_layer`, the loop
```
while not cz_layer:
        qubits = cast(Iterable[devices.GridQubit], circuit.all_qubits())
        cz_layer = list(_make_cz_layer(qubits, layer_index))
        layer_index += 1
```
would never end.

My suggestion would be change `assert 1 <= n_rows <= 11` in `generate_boixo_2018_supremacy_circuits_v2_bristlecone` to `assert 2 <= n_rows <= 11`, since it does not make anysense to have one-qubit cz layer in the first place.

### PR DESCRIPTION
**Pull request by tbcdebug**
Fixes #2295

### CODE REVIEW

**Comment by tbcdebug** [comment]
@googlebot I signed it!

**Comment by tbcdebug** [comment]
hmm, I wonder why Travis CI build failed. This change seems to be perfectly harmless

**Comment by vtomole** [comment]
@tbcdebug We've flaking on Windows checks lately. Rerunning.

**Comment by vtomole** [comment]
@Strilanc It seems like the other powershell command broke today.

**Comment by Strilanc** [comment]
Normally I'd add a test checking that you caught the failure, but this is fine as is. Thanks for the fix.

**Pull request merged**
