### PR TITLE
Remove foxtail references

### PR DESCRIPTION
**Pull request by carthick**

### CODE REVIEW

**Comment by pavoljuhas** [comment]
Thank you for the catch.  Can you please clean the other Foxtail references as well?

I suggest to delete the Foxtail paragraph here -

https://github.com/quantumlib/Cirq/blob/3ac3c30d0db92152a25ef2cf528454f561f4bf16/docs/google/devices.md?plain=1#L336-L340

and substitute `Sycamore` at
https://github.com/quantumlib/Cirq/blob/3ac3c30d0db92152a25ef2cf528454f561f4bf16/docs/dev/development.md?plain=1#L418

**Comment by carthick** [comment]
> Thank you for the catch. Can you please clean the other Foxtail references as well?
> 
> I suggest to delete the Foxtail paragraph here -
> 
> https://github.com/quantumlib/Cirq/blob/3ac3c30d0db92152a25ef2cf528454f561f4bf16/docs/google/devices.md?plain=1#L336-L340
> 
> and substitute `Sycamore` at
> 
> https://github.com/quantumlib/Cirq/blob/3ac3c30d0db92152a25ef2cf528454f561f4bf16/docs/dev/development.md?plain=1#L418

Sure @pavoljuhas , I have updated the PR, please let me know if anything need to update.

**Review by wcourtney — APPROVED** [review]
Thanks for the cleanup :-)

**Review by pavoljuhas — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
