### PR TITLE
Add `functools.cached_property` backport

### PR DESCRIPTION
**Pull request by maffoo**
The [`@functools.cached_property`](https://docs.python.org/3/library/functools.html#functools.cached_property) decorator is really useful but not currently available in cirq since it was introduced in python 3.8 but we still support python 3.7. This adds `backports.cached_property` to make cached properties available in python 3.7, using import logic in `cirq._compat` to get it from the standard library or backport module, as needed.

### CODE REVIEW

**Comment by MichaelBroughton** [comment]
Does doing something like:

```python3
@property
@functools.lru_cache(maxsize=None)
def thing(x):
   stuff(x)
```
not work ?

**Comment by maffoo** [comment]
@MichaelBroughton, no, that doesn't work generally because it it requires all parameters to be hashable, including `self`. It also attaches the cache to the class, so that the cache will grow without bound if you create lots of instances. With `cached_property` the value is cached on the instance instead, so values get gc'd with the instances they are attached to.

**Comment by MichaelBroughton** [comment]
Fair enough. Last question: Why should it be Cirq's responsibility to provide this wrapper for `cached_property` ? Do we have use cases in the actual code base ? I don't think we should expose `cirq.cached_property` just as an unrelated convenience method for users otherwise.

**Comment by maffoo** [comment]
Agree we shouldn't export this at the top level, that's why I put it in `cirq._compat` but did not export outside of that. There are quite a few places where we implement _ad hoc_ property caching that I think could be converted to use this, but it's more of an internal implementation convenience than something we want to expose to users.

**Review by MichaelBroughton — APPROVED** [review]

**Pull request merged**
