### PR TITLE
Community release

### PR DESCRIPTION
**Pull request by MichaelBroughton**
Learning how the release process works for Cirq from @balopat was an interesting experience. Lots of things were smooth and automated + easy. One thing that wasn't smooth and automated was having to manually document the bigger feature adds and reviewing commit history for breaking change tags etc. What do people think of starting to crowdsource the summary of changes as they happen in a text document over time ? 

Whenever someone opens a PR they add a little description into one of the sections of the release document as well.

### CODE REVIEW

**Comment by balopat** [comment]
I like it - however we should be clear about when we mandate this and when it is okay to skip the release notes (e.g. revert, typos, minimal fixes).

**Comment by tanujkhattar** [comment]
From Cirq Sync:
- Let's see if we can automate it

**Comment by tanujkhattar** [comment]
@MichaelBroughton Please reopen once the exploration around automating the process is done.

**Comment by vtomole** [comment]
@MichaelBroughton I don't know how your search has been going so far: maybe you've run into https://github.com/orhun/git-cliff. We'll have police every PR message to make sure they follow a a template; maybe with some git hooks. I think we'd have to do this no matter what if we want to automate the release notes.

**Comment by vtomole** [comment]
@MichaelBroughton We can now create automatic release notes via https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/

**Comment by MichaelBroughton** [comment]
Ohhhh nice find @vtomole . Lets be sure and scope this out to try for the next release!

**Pull request closed without merging**
