### PR TITLE
Move cirq/ops/moment.py to cirq/circuits/moment.py

### LINKED ISSUE #4665: Move cirq/ops/moment.py to cirq/circuits/moment.py ?
**Description of the issue**
Moments are a building blocks for circuits and should belong in the cirq/circuits/* instead of cirq/ops/*. This issue is to discuss this proposal and, if agreed, move the files following a deprecation cycle.

```
0.13.0.dev
```

### PR DESCRIPTION
**Pull request by tanujkhattar**
Fixes #4665 

TODO: Figure out a way to deprecate the old submodule s.t. we don't directly break all code of the form `cirq.ops.moment.Moment` / `cirq.ops.Moment` / `from cirq.ops import Moment`. 
NOTE: DO NOT MERGE!

### CODE REVIEW

**Comment by pavoljuhas** [comment]
@tanujkhattar - this should be unblocked after https://github.com/quantumlib/Cirq/pull/4920.

I will prepare a follow up on top of that PR.

**Comment by pavoljuhas** [comment]
@tanujkhattar - please consider adding the following branch to this PR:
```
git pull https://github.com/pavoljuhas/Cirq move_moment-next
```

New commits:

6dfd212d Replace deprecated `cirq.ops.Moment` in examples
8c28135e Fix leftover ops.Moment reference
3f20f1be Deprecate module cirq.ops.moment and cirq.ops.Moment
578041d7 Merge branch #4920 'fix-attributes-and-spec-after-deprecation' into move_moment
e63dbfea Merge branch 'master' into move_moment

**Comment by pavoljuhas** [comment]
Updated follow-up branch after #4920 got merged to master (please disregard https://github.com/quantumlib/Cirq/pull/4838#issuecomment-1026643565)

```
git pull https://github.com/pavoljuhas/Cirq move_moment-next-2
```

New commits:

fd8d2868 Replace deprecated `cirq.ops.Moment` in examples
f53080f3 Fix leftover ops.Moment reference
bad0e9c2 Deprecate module cirq.ops.moment and cirq.ops.Moment
40a6b2e8 Merge branch 'master' into move_moment-next-2

**Comment by tanujkhattar** [comment]
@pavoljuhas Thanks for taking this up. I'll close this PR and you can create a new PR with your branch and I'll be happy to review it. Thanks!

**Comment by pavoljuhas** [comment]
@tanujkhattar - done, please see https://github.com/quantumlib/Cirq/pull/4932

**Pull request closed without merging**
